tinyMCE.addI18n('is.advimage_dlg',{
tab_general:"Almennt",
tab_appearance:"\u00DAtlit",
tab_advanced:"N\u00E1nar",
general:"Almennt",
title:"Titill",
preview:"Forsko\u00F0un",
constrain_proportions:"Halda hlutf\u00F6llum",
langdir:"\u00C1tt tungum\u00E1ls",
langcode:"K\u00F3\u00F0i tungum\u00E1ls",
long_desc:"L\u00F6ng l\u00FDsing \u00E1 hlekki",
style:"St\u00EDll",
classes:"Klasar",
ltr:"Vinstri til h\u00E6gri",
rtl:"H\u00E6gri til vinstri",
id:"Id",
map:"Image map",
swap_image:"Skipta mynd \u00FAt",
alt_image:"\u00D6nnur mynd",
mouseover:"\u00FEegar m\u00FAs er yfir",
mouseout:"\u00FEegar m\u00FAs fer af",
misc:"\u00DDmislegt",
example_img:"Birting prufumyndar",
missing_alt:"Ertu viss um a\u00F0 halda \u00E1fram \u00E1n l\u00FDsingu myndar? \u00C1n hennar er myndin \u00F3a\u00F0genginleg fyrir suma notendur me\u00F0 skj\u00E1lesara, texta vafra e\u00F0a me\u00F0 sl\u00F6kkt \u00E1 birtingu mynda \u00ED vafranum s\u00EDnum.",
dialog_title:"Setja inn/breyta mynd",
src:"Sl\u00F3\u00F0 \u00E1 mynd",
alt:"L\u00FDsing",
list:"Myndalisti",
border:"Rammi",
dimensions:"St\u00E6r\u00F0ir",
vspace:"L\u00F3\u00F0r\u00E9tt loftun",
hspace:"L\u00E1r\u00E9tt loftun",
align:"J\u00F6fnun",
align_baseline:"Baseline",
align_top:"Top",
align_middle:"Middle",
align_bottom:"Bottom",
align_texttop:"Text top",
align_textbottom:"Text bottom",
align_left:"Left",
align_right:"Right",
image_list:"Image list"
});