build:
    environment:
        php:
            version: 5.6
    dependencies:
        before:
            - cd htdocs/
            - composer install
            - cd ..
    tests:
        override:
            -
                command: './bin/console code:sniff --xml'
                analysis:
                    file: './tests/cs-data'
                    format: 'php-cs-checkstyle'

filter:
    paths:
        - 'htdocs/*'
        - 'local/*'
    excluded_paths:
        - 'bin/*'
        - 'doc/*'
        - 'htdocs/okapi/*'
        - 'htdocs/resource2/tinymce/*'
        - 'htdocs/resource2/ocstyle/js/communicator-api/*'
        - 'htdocs/resource2/ocstyle/js/enlargeit/*'
        - 'htdocs/templates2/*'
    dependency_paths:
        - 'htdocs/vendor/*'

checks:
    php: true
    javascript: true
