tinyMCE.addI18n('is.advlink_dlg',{
title:"Setja inn/breyta hlekk",
url:"Sl\u00F3\u00F0",
target:"Target",
titlefield:"Titill",
is_email:"Sl\u00F3\u00F0in sem \u00FE\u00FA skr\u00E1\u00F0ir vir\u00F0ist vera netfang, vilt \u00FE\u00FA b\u00E6ta vi\u00F0 forskeytinu mailto:?",
is_external:"Sl\u00F3\u00F0in sem \u00FE\u00FA skr\u00E1\u00F0ir vir\u00F0ist vera sl\u00F3\u00F0 utan vefs, vilt \u00FE\u00FA b\u00E6ta vi\u00F0 forskeytinu http://?",
list:"Listi hlekkja",
general_tab:"Almennt",
popup_tab:"Sprettigluggi",
events_tab:"Vi\u00F0bur\u00F0ir",
advanced_tab:"N\u00E1nar",
general_props:"Almennir eiginleikar",
popup_props:"Eiginleikar sprettiglugga",
event_props:"Vi\u00F0bur\u00F0ir",
advanced_props:"Frekari eiginleikar",
popup_opts:"M\u00F6guleikar",
anchor_names:"Anchors",
target_same:"Opna \u00ED \u00FEessum glugga / ramma",
target_parent:"Opna \u00ED yfir glugga / ramma",
target_top:"Opna \u00ED efsta ramma (kemur \u00ED sta\u00F0inn fyrir alla ramma)",
target_blank:"Opna \u00ED n\u00FDjum glugga",
popup:"Javascript sprettigluggi",
popup_url:"Sl\u00F3\u00F0 sprettigluggans",
popup_name:"Heiti gluggans",
popup_return:"B\u00E6ta vi\u00F0 'return false'",
popup_scrollbars:"Birta runusl\u00E1",
popup_statusbar:"Birta st\u00F6\u00F0u sl\u00E1",
popup_toolbar:"Show toolbars",
popup_menubar:"Birta valmynd",
popup_location:"Birta vefsl\u00F3\u00F0",
popup_resizable:"Leyfa breytingu st\u00E6r\u00F0ar \u00E1 glugga",
popup_dependent:"Dependent (Mozilla/Firefox only)",
popup_size:"St\u00E6r\u00F0",
popup_position:"Sta\u00F0setning (X/Y)",
id:"Id",
style:"St\u00EDll",
classes:"Klasi",
target_name:"Target heiti",
langdir:"\u00C1tt tungum\u00E1ls",
target_langcode:"\u00C6tla\u00F0 tungum\u00E1l",
langcode:"K\u00F3\u00F0i tungum\u00E1ls",
encoding:"Target character encoding",
mime:"Target MIME type",
rel:"Relationship page to target",
rev:"Relationship target to page",
tabindex:"Tabindex",
accesskey:"Fl\u00FDtihnappur",
ltr:"Vinstri til h\u00E6gri",
rtl:"H\u00E6gri til vinstri",
link_list:"Listi hlekkja"
});