tinyMCE.addI18n('is.fullpage_dlg',{
title:"Valm\u00F6guleikar skjals",
meta_tab:"Almennt",
appearance_tab:"\u00DAtlit",
advanced_tab:"\u00CDtarlegt",
meta_props:"Meta uppl\u00FDsingar",
langprops:"Tungum\u00E1l",
meta_title:"Titill",
meta_keywords:"Leitaror\u00F0",
meta_description:"L\u00FDsing",
meta_robots:"Robots",
doctypes:"Doctype",
langcode:"Tungum\u00E1la k\u00F3\u00F0i",
langdir:"Tungum\u00E1la \u00E1tt",
ltr:"Vinstri til h\u00E6gri",
rtl:"H\u00E6gri til vinstri",
xml_pi:"XML declaration",
encoding:"Stafa enk\u00F3\u00F0un",
appearance_bgprops:"Bakgrunns m\u00F6guleikar",
appearance_marginprops:"innihalds sp\u00E1ss\u00EDa",
appearance_linkprops:"Litir \u00E1 hlekkjum",
appearance_textprops:"Text properties",
bgcolor:"Bakgrunnslitur",
bgimage:"Bakgrunnsmynd",
left_margin:"vinstri sp\u00E1ss\u00EDa",
right_margin:"H\u00E6gri sp\u00E1ss\u00EDa",
top_margin:"Top sp\u00E1ss\u00EDa",
bottom_margin:"Botn sp\u00E1ss\u00EDa",
text_color:"Textalitur",
font_size:"Stafast\u00E6r\u00F0",
font_face:"Stafager\u00F0",
link_color:"Litur \u00E1 hlekk",
hover_color:"hover litur",
visited_color:"Heims\u00F3ttur litur",
active_color:"Virkur litur",
textcolor:"Litur",
fontsize:"Stafast\u00E6r\u00F0",
fontface:"Stafa fj\u00F6lskylda",
meta_index_follow:"Index and follow the links",
meta_index_nofollow:"Index and don't follow the links",
meta_noindex_follow:"Do not index but follow the links",
meta_noindex_nofollow:"Do not index and don\'t follow the links",
appearance_style:"St\u00EDlsni\u00F0 og eiginleikar",
stylesheet:"St\u00EDlsni\u00F0",
style:"St\u00EDll",
author:"H\u00F6fundur",
copyright:"Eignar\u00E9ttur",
add:"B\u00E6ta vi\u00F0 n\u00FDjum hlut",
remove:"Fjarl\u00E6gja valinn hlut",
moveup:"F\u00E6ra valinn hlut upp",
movedown:"F\u00E6ra valinn hlut ni\u00F0ur",
head_elements:"A\u00F0al hlutur",
info:"Uppl\u00FDsingar",
add_title:"Titill hluts",
add_meta:"Meta element",
add_script:"Script element",
add_style:"Style element",
add_link:"Link element",
add_base:"Base element",
add_comment:"B\u00E6ta vi\u00F0 athugasemd",
title_element:"Titill hluts",
script_element:"Script element",
style_element:"Style element",
base_element:"Base element",
link_element:"Link element",
meta_element:"Meta element",
comment_element:"Comment",
src:"Src",
language:"Tungum\u00E1l",
href:"Href",
target:"\u00C1\u00E6tlunarsta\u00F0ur",
type:"Tegund",
charset:"stafasett",
defer:"V\u00EDsun",
media:"Margmi\u00F0lun",
properties:"Eiginleikar",
name:"Nafn",
value:"Value",
content:"Innihald",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Almennt",
advanced_props:"\u00CDtarlegt"
});