<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * Create Query for Static PageBlocks
     *
     * @param string $slug
     * @param null $filter
     * @param null $sort
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getPageBlocksBySlugQueryBuilder($slug, $filter = null, $sort = null)
    {
        $qb = $this->createQueryBuilder('page_blocks_by_slug');

        $qb->select(['pageGroup', 'pageBlocks']);
        $qb->from('AppBundle:PageGroup', 'pageGroup')
            ->leftJoin('pageGroup.pageBlocks', 'pageBlocks')
            ->where('pageGroup.slug = :slug')
            ->setParameter('slug', $slug);

        if ($filter) {
            $qb->andWhere($filter);
        }

        if ($sort) {
            $qb->addOrderBy($sort);
        } else {
            $qb->addOrderBy('pageBlocks.position', 'ASC');
        }

        return $qb;
    }

    /**
     * GetBlocksBySlugQuery
     *
     * @param string $slug
     * @param null $filter
     * @param null $sort
     *
     * @return \Doctrine\ORM\Query
     */
    public function getPageBlocksBySlugQuery($slug, $filter = null, $sort = null)
    {
        return $this->getPageBlocksBySlugQueryBuilder($slug, $filter, $sort)->getQuery();
    }
}
