<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * Create Query for Static PageBlocks
     *
     * @param string $slug
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getPageBlocksBySlugQueryBuilder($slug)
    {
        $qb = $this->createQueryBuilder('page_blocks_by_slug');

        $qb->select(['page_group_id', 'page_blocks']);
        $qb->from('AppBundle:PageGroup', 'pageGroup')
            ->leftJoin('pageGroup.pageBlocks', 'pageBlocks')
            ->where('pageGroup.slug = :slug')
            ->setParameter('slug', $slug);

        return $qb;
    }

    /**
     * GetBlocksBySlugQuery
     *
     * @param string $slug
     *
     * @return \Doctrine\ORM\Query
     */
    public function getPageBlocksBySlugQuery($slug)
    {
        return $this->getPageBlocksBySlugQueryBuilder($slug)->getQuery();
    }
}
