-- Table countries_list_default
SET NAMES 'utf8';
TRUNCATE TABLE `countries_list_default`;
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'AT');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'BE');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'CH');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'CZ');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'DE');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'DK');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'ES');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'FR');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'GB');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'GR');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'HR');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'IT');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'LI');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'LU');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'NL');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'NO');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'PL');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'RO');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'SA');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'SE');
INSERT INTO `countries_list_default` (`lang`, `show`) VALUES ('DE', 'US');
