-- Table countries
SET NAMES 'utf8';
TRUNCATE TABLE `countries`;
INSERT INTO `countries` (`short`, `name`, `trans_id`, `de`, `en`, `list_default_de`, `sort_de`, `list_default_en`, `sort_en`) VALUES
('AD', 'Andorra', '447', 'Andorra', 'Andorra', '0', 'andorra', '0', 'andorra'),
('AE', 'United Arab Emirates', '446', 'Vereinigte Arabische Emirate', 'United Arab Emirates', '0', 'arabische emirate, vereinigte', '0', 'arab emirates, united'),
('AF', 'Afghanistan', '445', 'Afghanistan', 'Afghanistan', '0', 'afghanistan', '0', 'afghanistan'),
('AG', 'Antigua And Barbuda', '444', 'Antigua und Barbuda', 'Antigua And Barbuda', '0', 'antigua und barbuda', '0', 'antigua and barbuda'),
('AI', 'Anguilla', '443', 'Anguilla', 'Anguilla', '0', 'anguilla', '0', 'anguilla'),
('AL', 'Albania', '442', 'Albanien', 'Albania', '0', 'albanien', '0', 'albania'),
('AM', 'Armenia', '441', 'Armenien', 'Armenia', '0', 'armenien', '0', 'armenia'),
('AN', 'Netherlands Antilles', '440', 'Niederländische Antillen', 'Netherlands Antilles', '0', 'antillen, niederlaendische', '0', 'netherlands antilles'),
('AO', 'Angola', '439', 'Angola', 'Angola', '0', 'angola', '0', 'angola'),
('AR', 'Argentina', '438', 'Argentinien', 'Argentina', '0', 'argentinien', '0', 'argentina'),
('AS', 'American Samoa', '437', 'Amerikanisch-Samoa', 'American Samoa', '0', 'samoa-amerikanisch', '1', 'american samoa'),
('AT', 'Austria', '436', 'Österreich', 'Austria', '1', 'oesterreich', '0', 'austria'),
('AU', 'Australia', '435', 'Australien', 'Australia', '0', 'australien', '1', 'australia'),
('AW', 'Aruba', '434', 'Aruba', 'Aruba', '0', 'aruba', '0', 'aruba'),
('AZ', 'Azerbaijan', '433', 'Aserbaidschan', 'Azerbaijan', '0', 'aserbaidschan', '0', 'azerbaijan'),
('BA', 'Bosnia And Herzegowina', '432', 'Bosnien-Herzegowina', 'Bosnia And Herzegowina', '0', 'bosnien-herzegowina', '0', 'bosnia and herzegowina'),
('BB', 'Barbados', '431', 'Barbados', 'Barbados', '0', 'barbados', '0', 'barbados'),
('BD', 'Bangladesh', '430', 'Bangladesch', 'Bangladesh', '0', 'bangladesch', '0', 'bangladesh'),
('BE', 'Belgium', '429', 'Belgien', 'Belgium', '1', 'belgien', '0', 'belgium'),
('BF', 'Burkina Faso', '428', 'Burkina Faso', 'Burkina Faso', '0', 'burkina faso', '0', 'burkina faso'),
('BG', 'Bulgaria', '427', 'Bulgarien', 'Bulgaria', '0', 'bulgarien', '0', 'bulgaria'),
('BH', 'Bahrain', '426', 'Bahrain', 'Bahrain', '0', 'bahrain', '0', 'bahrain'),
('BI', 'Burundi', '425', 'Burundi', 'Burundi', '0', 'burundi', '0', 'burundi'),
('BJ', 'Benin', '424', 'Benin', 'Benin', '0', 'benin', '0', 'benin'),
('BM', 'Bermuda', '423', 'Bermuda', 'Bermuda', '0', 'bermuda', '0', 'bermuda'),
('BN', 'Brunei Darussalam', '422', 'Brunei', 'Brunei Darussalam', '0', 'brunei', '0', 'brunei darussalam'),
('BO', 'Bolivia', '421', 'Bolivien', 'Bolivia', '0', 'bolivien', '0', 'bolivia'),
('BR', 'Brazil', '420', 'Brasilien', 'Brazil', '0', 'brasilien', '0', 'brazil'),
('BS', 'Bahamas', '419', 'Bahamas', 'Bahamas', '0', 'bahamas', '0', 'bahamas'),
('BT', 'Bhutan', '418', 'Bhutan', 'Bhutan', '0', 'bhutan', '0', 'bhutan'),
('BV', 'Bouvet Island', '417', 'die Bouvetinseln', 'Bouvet Island', '0', 'bouvetinseln, die', '0', 'bouvet island'),
('BW', 'Botswana', '416', 'Botsuana', 'Botswana', '0', 'botsuana', '0', 'botswana'),
('BY', 'Belarus', '415', 'Belarus (Weißrußland)', 'Belarus', '0', 'belarus (weissrussland)', '0', 'belarus'),
('BZ', 'Belize', '414', 'Belize', 'Belize', '0', 'belize', '0', 'belize'),
('CA', 'Canada', '413', 'Kanada', 'Canada', '0', 'kanada', '1', 'canada'),
('CC', 'Cocos (Keeling) Islands', '412', 'Kokosinseln', 'Cocos (Keeling) Islands', '0', 'kokosinseln', '0', 'cocos (keeling) islands'),
('CF', 'Central African Republic', '411', 'Zentralafrikanische Republik', 'Central African Republic', '0', 'zentralafrikanische republik', '0', 'central african republic'),
('CG', 'Congo', '410', 'Kongo', 'Congo', '0', 'kongo', '0', 'congo'),
('CH', 'Switzerland', '409', 'Schweiz', 'Switzerland', '1', 'schweiz', '0', 'switzerland'),
('CI', 'Cote d\'Ivoire', '408', 'Elfenbeinküste', 'Cote d\'Ivoire', '0', 'elfenbeinkueste', '0', 'Zimbabwe'),
('CK', 'Cook Islands', '407', 'Cookinseln', 'Cook Islands', '0', 'cookinseln', '0', 'cook islands'),
('CL', 'Chile', '406', 'Chile', 'Chile', '0', 'chile', '0', 'chile'),
('CM', 'Cameroon', '405', 'Kamerun', 'Cameroon', '0', 'kamerun', '0', 'cameroon'),
('CN', 'China', '404', 'Volksrepublik China', 'China', '0', 'china, volksrepublik', '0', 'china'),
('CO', 'Colombia', '403', 'Kolumbien', 'Colombia', '0', 'kolumbien', '0', 'colombia'),
('CR', 'Costa Rica', '402', 'Costa Rica', 'Costa Rica', '0', 'costa rica', '0', 'costa rica'),
('CU', 'Cuba', '400', 'Kuba', 'Cuba', '0', 'kuba', '0', 'cuba'),
('CV', 'Cape Verde', '399', 'Kapverden', 'Cape Verde', '0', 'kapverden', '0', 'cape verde'),
('CX', 'Christmas Island', '398', 'Weihnachtsinseln', 'Christmas Island', '0', 'weihnachtsinseln', '0', 'christmas island'),
('CY', 'Cyprus', '397', 'Zypern', 'Cyprus', '0', 'zypern', '0', 'cyprus'),
('CZ', 'Czech Republic', '396', 'Tschechische Republik', 'Czech Republic', '1', 'tschechische republik', '0', 'czech republic'),
('DE', 'Germany', '395', 'Deutschland', 'Germany', '1', 'deutschland', '0', 'germany'),
('DJ', 'Djibouti', '394', 'Dschibuti', 'Djibouti', '0', 'dschibuti', '0', 'djibouti'),
('DK', 'Denmark', '393', 'Dänemark', 'Denmark', '1', 'daenemark', '0', 'denmark'),
('DO', 'Dominican Republic', '392', 'Dominikanische Republik', 'Dominican Republic', '0', 'dominikanische republik', '0', 'dominican republic'),
('DZ', 'Algeria', '391', 'Algerien', 'Algeria', '0', 'algerien', '0', 'algeria'),
('EC', 'Ecuador', '390', 'Ecuador', 'Ecuador', '0', 'ecuador', '0', 'ecuador'),
('EE', 'Estonia', '389', 'Estland', 'Estonia', '0', 'estland', '0', 'estonia'),
('EG', 'Egypt', '388', 'Ägypten', 'Egypt', '0', 'aegypten', '0', 'egypt'),
('EH', 'Western Sahara', '387', 'Westsahara', 'Western Sahara', '0', 'westsahara', '0', 'western sahara'),
('ER', 'Eritrea', '386', 'Eritrea', 'Eritrea', '0', 'eritrea', '0', 'eritrea'),
('ES', 'Spain', '385', 'Spanien', 'Spain', '1', 'spanien', '0', 'spain'),
('ET', 'Ethiopia', '384', 'Äthiopien', 'Ethiopia', '0', 'aethiopien', '0', 'ethiopia'),
('FI', 'Finland', '383', 'Finnland', 'Finland', '0', 'finnland', '0', 'finland'),
('FJ', 'Fiji', '382', 'Fidschi', 'Fiji', '0', 'fidschi', '0', 'fiji'),
('FK', 'Falkland Islands (Malvinas)', '381', 'Falklandinseln', 'Falkland Islands (Malvinas)', '0', 'falklandinseln', '0', 'falkland islands (malvinas)'),
('FM', 'Micronesia, Federated States Of', '380', 'Mikronesien', 'Micronesia, Federated States Of', '0', 'mikronesien', '0', 'micronesia, federated states of'),
('FO', 'Faroe Islands', '379', 'Färöer (zu Dänemark)', 'Faroe Islands', '0', 'faeroeer (zu daenemark)', '0', 'faroe islands'),
('FR', 'France', '378', 'Frankreich', 'France', '1', 'frankreich', '0', 'france'),
('GA', 'Gabon', '377', 'Gabun', 'Gabon', '0', 'gabun', '0', 'gabon'),
('GB', 'United Kingdom', '376', 'Großbritannien', 'United Kingdom', '0', 'grossbritannien', '1', 'united kingdom'),
('GD', 'Grenada', '375', 'Granada', 'Grenada', '0', 'granada', '0', 'grenada'),
('GE', 'Georgia', '374', 'Georgien', 'Georgia', '0', 'georgien', '0', 'georgia'),
('GF', 'French Guiana', '373', 'Guayana', 'French Guiana', '0', 'guayana', '0', 'french guiana'),
('GH', 'Ghana', '372', 'Ghana', 'Ghana', '0', 'ghana', '0', 'ghana'),
('GI', 'Gibraltar', '371', 'Gibraltar', 'Gibraltar', '0', 'gibraltar', '0', 'gibraltar'),
('GL', 'Greenland', '370', 'Grönland', 'Greenland', '0', 'groenland', '0', 'greenland'),
('GM', 'Gambia', '369', 'Gambia', 'Gambia', '0', 'gambia', '0', 'gambia'),
('GN', 'Guinea', '368', 'Guinea', 'Guinea', '0', 'guinea', '0', 'guinea'),
('GP', 'Guadeloupe', '367', 'Guadelope', 'Guadeloupe', '0', 'guadelope', '0', 'guadeloupe'),
('GR', 'Greece', '366', 'Griechenland', 'Greece', '0', 'griechenland', '0', 'greece'),
('GS', 'South Georgia And The South Sandwich Islands', '365', 'Südgeorgien und die Südlichen Sandwichinseln', 'South Georgia And The South Sandwich Islands', '0', 'suedgeorgien und die suedlichen sandwichinseln', '0', 'south georgia and the south sandwich islands'),
('GT', 'Guatemala', '364', 'Guatemala', 'Guatemala', '0', 'guatemala', '0', 'guatemala'),
('GU', 'Guam', '363', 'Guam', 'Guam', '0', 'guam', '0', 'guam'),
('GW', 'Guinea-Bissau', '362', 'Guinea-Bissau', 'Guinea-Bissau', '0', 'guinea-bissau', '0', 'guinea-bissau'),
('GY', 'Guyana', '361', 'Guyana', 'Guyana', '0', 'guyana', '0', 'guyana'),
('HK', 'Hong Kong', '360', 'Honkong', 'Hong Kong', '0', 'honkong', '0', 'hong kong'),
('HM', 'Heard And Mc Donald Islands', '359', 'Heard und McDonaldinseln', 'Heard And Mc Donald Islands', '0', 'heard und mcdonaldinseln', '0', 'heard and mc donald islands'),
('HN', 'Honduras', '358', 'Honduras', 'Honduras', '0', 'honduras', '0', 'honduras'),
('HR', 'Croatia', '357', 'Kroatien', 'Croatia', '0', 'kroatien', '0', 'croatia'),
('HT', 'Haiti', '356', 'Haiti', 'Haiti', '0', 'haiti', '0', 'haiti'),
('HU', 'Hungary', '355', 'Ungarn', 'Hungary', '0', 'ungarn', '0', 'hungary'),
('ID', 'Indonesia', '354', 'Indonesien', 'Indonesia', '0', 'indonesien', '0', 'indonesia'),
('IE', 'Ireland', '353', 'Irland', 'Ireland', '0', 'irland', '0', 'ireland'),
('IL', 'Israel', '352', 'Israel', 'Israel', '0', 'israel', '0', 'israel'),
('IN', 'India', '351', 'Indien', 'India', '0', 'indien', '0', 'india'),
('IO', 'British Indian Ocean Territory', '350', 'Britisches Territorium im Indischen Ozean', 'British Indian Ocean Territory', '0', 'britisches territorium im indischen ozean', '0', 'british indian ocean territory'),
('IQ', 'Iraq', '349', 'Irak', 'Iraq', '0', 'irak', '0', 'iraq'),
('IR', 'Iran (Islamic Republic Of)', '348', 'Iran', 'Iran (Islamic Republic Of)', '0', 'iran', '0', 'iran (islamic republic of)'),
('IS', 'Iceland', '347', 'Island', 'Iceland', '0', 'island', '0', 'iceland'),
('IT', 'Italy', '346', 'Italien', 'Italy', '1', 'italien', '0', 'italy'),
('JM', 'Jamaica', '345', 'Jamaika', 'Jamaica', '0', 'jamaika', '0', 'jamaica'),
('JO', 'Jordan', '344', 'Jordanien', 'Jordan', '0', 'jordanien', '0', 'jordan'),
('JP', 'Japan', '343', 'Japan', 'Japan', '0', 'japan', '0', 'japan'),
('KE', 'Kenya', '342', 'Kenia', 'Kenya', '0', 'kenia', '0', 'kenya'),
('KG', 'Kyrgyzstan', '341', 'Kirgistan', 'Kyrgyzstan', '0', 'kirgistan', '0', 'kyrgyzstan'),
('KH', 'Cambodia', '340', 'Kambodscha', 'Cambodia', '0', 'kambodscha', '0', 'cambodia'),
('KI', 'Kiribati', '339', 'Kiribati', 'Kiribati', '0', 'kiribati', '0', 'kiribati'),
('KM', 'Comoros', '338', 'Komoren', 'Comoros', '0', 'komoren', '0', 'comoros'),
('KN', 'Saint Kitts And Nevis', '337', 'St. Kitts und Nevis', 'Saint Kitts And Nevis', '0', 'st. kitts und nevis', '0', 'saint kitts and nevis'),
('KP', 'Korea, Democratic People\'s Republic Of', '336', 'Demokratische Volksrepublik Korea', 'Korea, Democratic People\'s Republic Of', '0', 'korea, demokratische volksrepublik', '0', 'Zimbabwe'),
('KR', 'Korea, Republic Of', '335', 'Republik Korea', 'Korea, Republic Of', '0', 'korea, republik', '0', 'korea, republic of'),
('KW', 'Kuwait', '334', 'Kuwait', 'Kuwait', '0', 'kuwait', '0', 'kuwait'),
('KY', 'Cayman Islands', '333', 'Kaimaninseln', 'Cayman Islands', '0', 'kaimaninseln', '0', 'cayman islands'),
('KZ', 'Kazakhstan', '332', 'Kasachstan', 'Kazakhstan', '0', 'kasachstan', '0', 'kazakhstan'),
('LA', 'Lao People\'s Democratic Republic', '331', 'Laos', 'Lao People\'s Democratic Republic', '0', 'laos', '0', 'Zimbabwe'),
('LB', 'Lebanon', '330', 'Libanon', 'Lebanon', '0', 'libanon', '0', 'lebanon'),
('LC', 'Saint Lucia', '329', 'St. Lucia', 'Saint Lucia', '0', 'st. lucia', '0', 'saint lucia'),
('LI', 'Liechtenstein', '328', 'Liechtenstein', 'Liechtenstein', '1', 'liechtenstein', '0', 'liechtenstein'),
('LK', 'Sri Lanka', '327', 'Sri Lanka', 'Sri Lanka', '0', 'sri lanka', '0', 'sri lanka'),
('LR', 'Liberia', '326', 'Liberia', 'Liberia', '0', 'liberia', '0', 'liberia'),
('LS', 'Lesotho', '325', 'Lesotho', 'Lesotho', '0', 'lesotho', '0', 'lesotho'),
('LT', 'Lithuania', '324', 'Litauen', 'Lithuania', '0', 'litauen', '0', 'lithuania'),
('LU', 'Luxembourg', '323', 'Luxemburg', 'Luxembourg', '1', 'luxemburg', '0', 'luxembourg'),
('LV', 'Latvia', '322', 'Lettland', 'Latvia', '0', 'lettland', '0', 'latvia'),
('LY', 'Libyan Arab Jamahiriya', '321', 'Libyen', 'Libyan Arab Jamahiriya', '0', 'libyen', '0', 'libyan arab jamahiriya'),
('MA', 'Morocco', '320', 'Marokko', 'Morocco', '0', 'marokko', '0', 'morocco'),
('MC', 'Monaco', '319', 'Monaco', 'Monaco', '0', 'monaco', '0', 'monaco'),
('MD', 'Moldova, Republic Of', '318', 'Moldau', 'Moldova, Republic Of', '0', 'moldau', '0', 'moldova, republic of'),
('ME', 'Montenegro', '856', 'Montenegro', 'Montenegro', '0', 'montenegro', '0', 'montenegro'),
('MG', 'Madagascar', '317', 'Madagaskar', 'Madagascar', '0', 'madagaskar', '0', 'madagascar'),
('MH', 'Marshall Islands', '316', 'Marshallinseln', 'Marshall Islands', '0', 'marshallinseln', '0', 'marshall islands'),
('MK', 'Macedonia, The Former Yugoslav Republic Of', '315', 'Mazedonien', 'Macedonia, The Former Yugoslav Republic Of', '0', 'mazedonien', '0', 'macedonia, the former yugoslav republic of'),
('ML', 'Mali', '314', 'Mali', 'Mali', '0', 'mali', '0', 'mali'),
('MM', 'Myanmar', '313', 'Myanmar', 'Myanmar', '0', 'myanmar', '0', 'myanmar'),
('MN', 'Mongolia', '312', 'Mongolei', 'Mongolia', '0', 'mongolei', '0', 'mongolia'),
('MO', 'Macau', '311', 'Macau', 'Macau', '0', 'macau', '0', 'macau'),
('MP', 'Northern Mariana Islands', '310', 'Marianen', 'Northern Mariana Islands', '0', 'marianen', '0', 'northern mariana islands'),
('MQ', 'Martinique', '309', 'Martinique', 'Martinique', '0', 'martinique', '0', 'martinique'),
('MR', 'Mauritania', '308', 'Mauretanien', 'Mauritania', '0', 'mauretanien', '0', 'mauritania'),
('MS', 'Montserrat', '307', 'Montserrat', 'Montserrat', '0', 'montserrat', '0', 'montserrat'),
('MT', 'Malta', '306', 'Malta', 'Malta', '0', 'malta', '0', 'malta'),
('MU', 'Mauritius', '305', 'Mauritius', 'Mauritius', '0', 'mauritius', '0', 'mauritius'),
('MV', 'Maldives', '304', 'Malediven', 'Maldives', '0', 'malediven', '0', 'maldives'),
('MW', 'Malawi', '303', 'Malwai', 'Malawi', '0', 'malwai', '0', 'malawi'),
('MX', 'Mexico', '302', 'Mexiko', 'Mexico', '0', 'mexiko', '0', 'mexico'),
('MY', 'Malaysia', '301', 'Malaysia', 'Malaysia', '0', 'malaysia', '0', 'malaysia'),
('MZ', 'Mozambique', '300', 'Mosambik', 'Mozambique', '0', 'mosambik', '0', 'mozambique'),
('NA', 'Namibia', '299', 'Namibia', 'Namibia', '0', 'namibia', '0', 'namibia'),
('NC', 'New Caledonia', '298', 'Neukaledonien', 'New Caledonia', '0', 'neukaledonien', '0', 'new caledonia'),
('NE', 'Niger', '297', 'Niger', 'Niger', '0', 'niger', '0', 'niger'),
('NF', 'Norfolk Island', '296', 'Norfolkinseln', 'Norfolk Island', '0', 'norfolkinseln', '0', 'norfolk island'),
('NG', 'Nigeria', '295', 'Nigeria', 'Nigeria', '0', 'nigeria', '0', 'nigeria'),
('NI', 'Nicaragua', '294', 'Nicaragua', 'Nicaragua', '0', 'nicaragua', '0', 'nicaragua'),
('NL', 'Netherlands', '293', 'Niederlande', 'Netherlands', '1', 'niederlande', '0', 'netherlands'),
('NO', 'Norway', '292', 'Norwegen', 'Norway', '0', 'norwegen', '0', 'norway'),
('NP', 'Nepal', '291', 'Nepal', 'Nepal', '0', 'nepal', '0', 'nepal'),
('NR', 'Nauru', '290', 'Nauru', 'Nauru', '0', 'nauru', '0', 'nauru'),
('NU', 'Niue', '289', 'Niue', 'Niue', '0', 'niue', '0', 'niue'),
('NZ', 'New Zealand', '288', 'Neuseeland', 'New Zealand', '0', 'neuseeland', '0', 'new zealand'),
('OM', 'Oman', '287', 'Oman', 'Oman', '0', 'oman', '0', 'oman'),
('PA', 'Panama', '286', 'Panama', 'Panama', '0', 'panama', '0', 'panama'),
('PE', 'Peru', '285', 'Peru', 'Peru', '0', 'peru', '0', 'peru'),
('PF', 'French Polynesia', '284', 'Französisch-Polynesien', 'French Polynesia', '0', 'franzoesisch-polynesien', '0', 'french polynesia'),
('PG', 'Papua New Guinea', '283', 'Papua-Neuguinea', 'Papua New Guinea', '0', 'papua-neuguinea', '0', 'papua new guinea'),
('PH', 'Philippines', '282', 'Philippinen', 'Philippines', '0', 'philippinen', '0', 'philippines'),
('PK', 'Pakistan', '281', 'Pakistan', 'Pakistan', '0', 'pakistan', '0', 'pakistan'),
('PL', 'Poland', '280', 'Polen', 'Poland', '1', 'polen', '0', 'poland'),
('PM', 'St. Pierre And Miquelon', '279', 'St. Pierre und Miquelon', 'St. Pierre And Miquelon', '0', 'st. pierre und miquelon', '0', 'st. pierre and miquelon'),
('PN', 'Pitcairn', '278', 'die Pitcairninseln', 'Pitcairn', '0', 'pitcairninseln, die', '0', 'pitcairn'),
('PR', 'Puerto Rico', '277', 'Puerto Rico', 'Puerto Rico', '0', 'puerto rico', '0', 'puerto rico'),
('PT', 'Portugal', '276', 'Portugal', 'Portugal', '0', 'portugal', '0', 'portugal'),
('PW', 'Palau', '275', 'Palau', 'Palau', '0', 'palau', '0', 'palau'),
('PY', 'Paraguay', '274', 'Paraguay', 'Paraguay', '0', 'paraguay', '0', 'paraguay'),
('QA', 'Qatar', '273', 'Katar', 'Qatar', '0', 'katar', '0', 'qatar'),
('RE', 'Reunion', '272', 'Réunion', 'Reunion', '0', 'reunion', '0', 'reunion'),
('RO', 'Romania', '271', 'Rumänien', 'Romania', '0', 'rumaenien', '0', 'romania'),
('RS', 'Serbia', '857', 'Serbien', 'Serbia', '0', 'serbia', '0', 'serbia'),
('RU', 'Russian Federation', '270', 'Russische Föderation', 'Russian Federation', '0', 'russische foederation', '0', 'russian federation'),
('RW', 'Rwanda', '269', 'Ruanda', 'Rwanda', '0', 'ruanda', '0', 'rwanda'),
('SA', 'Saudi Arabia', '268', 'Saudi-Arabien', 'Saudi Arabia', '0', 'saudi-arabien', '0', 'saudi arabia'),
('SB', 'Solomon Islands', '267', 'Salomonen', 'Solomon Islands', '0', 'salomonen', '0', 'solomon islands'),
('SC', 'Seychelles', '266', 'Seychellen', 'Seychelles', '0', 'seychellen', '0', 'seychelles'),
('SD', 'Sudan', '265', 'Sudan', 'Sudan', '0', 'sudan', '0', 'sudan'),
('SE', 'Sweden', '264', 'Schweden', 'Sweden', '0', 'schweden', '0', 'sweden'),
('SG', 'Singapore', '263', 'Singapur', 'Singapore', '0', 'singapur', '0', 'singapore'),
('SH', 'St. Helena', '262', 'St. Helena', 'St. Helena', '0', 'st. helena', '0', 'st. helena'),
('SI', 'Slovenia', '261', 'Slowenien', 'Slovenia', '0', 'slowenien', '0', 'slovenia'),
('SJ', 'Svalbard And Jan Mayen Islands', '260', 'Svalbard und Jan Mayen', 'Svalbard And Jan Mayen Islands', '0', 'svalbard und jan mayen', '0', 'svalbard and jan mayen islands'),
('SK', 'Slovakia', '259', 'Slowakai', 'Slovakia', '0', 'slowakai', '0', 'slovakia'),
('SL', 'Sierra Leone', '258', 'Sierra Leone', 'Sierra Leone', '0', 'sierra leone', '0', 'sierra leone'),
('SM', 'San Marino', '257', 'San Marino', 'San Marino', '0', 'san marino', '0', 'san marino'),
('SN', 'Senegal', '256', 'Senegal', 'Senegal', '0', 'senegal', '0', 'senegal'),
('SO', 'Somalia', '252', 'Somalia', 'Somalia', '0', 'somalia', '0', 'somalia'),
('SR', 'Suriname', '251', 'Suriname', 'Suriname', '0', 'suriname', '0', 'suriname'),
('ST', 'Sao Tome And Principe', '250', 'Sao Tomé und Principe', 'Sao Tome And Principe', '0', 'sao tomé und principe', '0', 'sao tome and principe'),
('SV', 'El Salvador', '249', 'El Salvador', 'El Salvador', '0', 'el salvador', '0', 'el salvador'),
('SY', 'Syrian Arab Republic', '243', 'Syrien', 'Syrian Arab Republic', '0', 'syrien', '0', 'syrian arab republic'),
('SZ', 'Swaziland', '242', 'Swasiland', 'Swaziland', '0', 'swasiland', '0', 'swaziland'),
('TC', 'Turks And Caicos Islands', '240', 'Turks- und Caicosinseln', 'Turks And Caicos Islands', '0', 'turks- und caicosinseln', '0', 'turks and caicos islands'),
('TD', 'Chad', '239', 'Tschad', 'Chad', '0', 'tschad', '0', 'chad'),
('TF', 'French Southern Territories', '238', 'Französische Süd- und Antarktisgebiete', 'French Southern Territories', '0', 'franzoesische sued- und antarktisgebiete', '0', 'french southern territories'),
('TG', 'Togo', '237', 'Togo', 'Togo', '0', 'togo', '0', 'togo'),
('TH', 'Thailand', '236', 'Thailand', 'Thailand', '0', 'thailand', '0', 'thailand'),
('TJ', 'Tajikistan', '235', 'Tadschikistan', 'Tajikistan', '0', 'tadschikistan', '0', 'tajikistan'),
('TK', 'Tokelau', '234', 'Tokelau', 'Tokelau', '0', 'tokelau', '0', 'tokelau'),
('TM', 'Turkmenistan', '233', 'Turkmenistan', 'Turkmenistan', '0', 'turkmenistan', '0', 'turkmenistan'),
('TN', 'Tunisia', '231', 'Tunesien', 'Tunisia', '0', 'tunesien', '0', 'tunisia'),
('TO', 'Tonga', '223', 'Tonga', 'Tonga', '0', 'tonga', '0', 'tonga'),
('TR', 'Turkey', '215', 'Türkei', 'Turkey', '0', 'tuerkei', '0', 'turkey'),
('TT', 'Trinidad And Tobago', '214', 'Trinidad und Tobago', 'Trinidad And Tobago', '0', 'trinidad und tobago', '0', 'trinidad and tobago'),
('TV', 'Tuvalu', '213', 'Tuvalu', 'Tuvalu', '0', 'tuvalu', '0', 'tuvalu'),
('TW', 'Taiwan, Province Of China', '212', 'Taiwan', 'Taiwan, Province Of China', '0', 'taiwan', '0', 'taiwan, province of china'),
('TZ', 'Tanzania, United Republic Of', '211', 'Tansania', 'Tanzania, United Republic Of', '0', 'tansania', '0', 'tanzania, united republic of'),
('UA', 'Ukraine', '210', 'Ukraine', 'Ukraine', '0', 'ukraine', '0', 'ukraine'),
('UG', 'Uganda', '209', 'Uganda', 'Uganda', '0', 'uganda', '0', 'uganda'),
('UM', 'United States Minor Outlying Islands', '204', 'Amerikanisch-Ozeanien', 'United States Minor Outlying Islands', '0', 'amerikanisch-ozeanien', '0', 'united states minor outlying islands'),
('US', 'United States', '203', 'Vereinigte Staaten', 'United States', '0', 'vereinigte staaten', '1', 'united states'),
('UY', 'Uruguay', '201', 'Uruguay', 'Uruguay', '0', 'uruguay', '0', 'uruguay'),
('UZ', 'Uzbekistan', '194', 'Usbekistan', 'Uzbekistan', '0', 'usbekistan', '0', 'uzbekistan'),
('VA', 'Vatican City State (Holy See)', '193', 'Vatikan (Heiliger Stuhl)', 'Vatican City State (Holy See)', '0', 'vatikan (heiliger stuhl)', '0', 'vatican city state (holy see)'),
('VC', 'Saint Vincent And The Grenadines', '192', 'St. Vincent und die Grenadinen', 'Saint Vincent And The Grenadines', '0', 'st. vincent und die grenadinen', '0', 'saint vincent and the grenadines'),
('VE', 'Venezuela', '185', 'Venezuela', 'Venezuela', '0', 'venezuela', '0', 'venezuela'),
('VG', 'Virgin Islands (British)', '184', 'die Britischen Jungferninseln', 'Virgin Islands (British)', '0', 'jungferninseln, die britischen', '0', 'virgin islands (british)'),
('VI', 'Virgin Islands (U.S.)', '183', 'die Amerikanischen Jungferninseln', 'Virgin Islands (U.S.)', '0', 'jungferninseln, die amerikanischen', '0', 'virgin islands (u.s.)'),
('VN', 'Viet Nam', '182', 'Vietnam', 'Viet Nam', '0', 'vietnam', '0', 'viet nam'),
('VU', 'Vanuatu', '181', 'Vanuatu', 'Vanuatu', '0', 'vanuatu', '0', 'vanuatu'),
('WF', 'Wallis And Futuna Islands', '179', 'Wallis und Futuna', 'Wallis And Futuna Islands', '0', 'wallis und futuna', '0', 'wallis and futuna islands'),
('WS', 'Samoa', '173', 'Samoa', 'Samoa', '0', 'samoa', '0', 'samoa'),
('YE', 'Yemen', '172', 'Jemen', 'Yemen', '0', 'jemen', '0', 'yemen'),
('YT', 'Mayotte', '165', 'Mayotte', 'Mayotte', '0', 'mayotte', '0', 'mayotte'),
('ZA', 'South Africa', '164', 'Südafrika', 'South Africa', '0', 'suedafrika', '0', 'south africa'),
('ZM', 'Zambia', '163', 'Sambia', 'Zambia', '0', 'sambia', '0', 'zambia'),
('ZW', 'Zimbabwe', '162', 'Simbabwe', 'Zimbabwe', '0', 'simbabwe', '0', 'zimbabwe');
