-- Table helppages
SET NAMES 'utf8';
TRUNCATE TABLE `helppages`;
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES
('activation', 'DE', 'Aktivierung'),
('additional_waypoints', 'DE', 'Zusätzliche Wegpunkte'),
('addtolist', 'DE', 'Cachelisten'),
('adoptcache', 'DE', 'Adoption'),
('adoptcache', 'EN', 'Adoptions'),
('cachelists', 'DE', 'Cachelisten'),
('change_statpic', 'DE', 'Statistikbild'),
('editcache', '*', '!articles.php?page=cacheinfo'),
('editdesc', 'DE', 'Beschreibungstext'),
('editlog', 'DE', 'Das Onlinelog'),
('error', 'DE', 'Fehlermeldungen'),
('helpindex', 'DE', 'Opencaching.de-Hilfe'),
('helpindex', 'EN', 'Opencaching Website Help'),
('log_cache', 'DE', 'Das Onlinelog'),
('login', 'DE', 'Login'),
('login', 'EN', 'EN/Login'),
('mailto', 'DE', 'Benutzerprofil#Emailversand'),
('*map2', 'DE', 'Cachekarte'),
('mydetails', 'DE', 'Benutzerprofil#Einstellungen'),
('myhome', 'DE', 'Benutzerprofil'),
('myignores', 'DE', 'Caches ignorieren'),
('mylists', 'DE', 'Cachelisten'),
('mytop5', 'DE', 'Empfehlungen'),
('myprofile', 'DE', 'Benutzerprofil#Einstellungen'),
('mystatpic', 'DE', 'Statistikbild'),
('mywatches', 'DE', 'Benachrichtigungen'),
('newcache', '*', '!articles.php?page=cacheinfo'),
('newdesc', 'DE', 'Beschreibungstext'),
('newlogpics', 'DE', 'Logbild-Galerien'),
('newpw', 'DE', 'Passwort'),
('npa', 'DE', 'Schutzgebiete'),
('npa', 'EN', 'Protected areas'),
('oconly', 'DE', 'OConly'),
('oconly81', 'DE', 'OConly-81'),
('opencaching', 'DE', 'Opencaching.de'),
('opencaching', 'EN', 'About Opencaching.de'),
('picture', 'DE', 'Bilder'),
('previewpics', 'DE', 'Vorschaubilder'),
('query', 'DE', 'Gespeicherte Suchen'),
('register', 'DE', 'Registrierung'),
('register', 'EN', 'Registration'),
('removelog_logowner', 'DE', 'Logeintrag löschen'),
('removelog_cacheowner', 'DE', 'Logeintrag löschen'),
('reportcache', 'DE', 'Cache melden'),
('report_reasons', 'DE', 'Cache melden#Wann melden.3F'),
('search', 'DE', 'Suchformular'),
('tops', 'DE', 'Empfehlungen'),
('tops', 'EN', 'Recommendations'),
('usernote', 'DE', 'Persönliche Notiz'),
('usertops', 'DE', 'Empfehlungen'),
('viewcache', 'DE', 'Listing'),
('viewlogs', 'DE', 'Das Onlinelog'),
('viewprofile', 'DE', 'Benutzerprofil'),
('viewprofile_pics', 'DE', 'Logbild-Galerien'),
('wikinews', 'DE', 'Hauptseite/Neue Artikel'),
('wikinews', 'EN', 'New articles');
