-- Table helppages
SET NAMES 'utf8';
TRUNCATE TABLE `helppages`;
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('activation', 'DE', 'Aktivierung');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('additional_waypoints', 'DE', 'Zusätzliche Wegpunkte');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('addtolist', 'DE', 'Cachelisten');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('adoptcache', 'DE', 'Adoption');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('adoptcache', 'EN', 'Adoptions');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('cachelists', 'DE', 'Cachelisten');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('change_statpic', 'DE', 'Statistikbild');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('editcache', '*', '!articles.php?page=cacheinfo');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('editdesc', 'DE', 'Beschreibungstext');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('editlog', 'DE', 'Das Onlinelog');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('error', 'DE', 'Fehlermeldungen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('helpindex', 'DE', 'Opencaching.de-Hilfe');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('helpindex', 'EN', 'Opencaching Website Help');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('log_cache', 'DE', 'Das Onlinelog');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('login', 'DE', 'Login');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('login', 'EN', 'EN/Login');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('mailto', 'DE', 'Benutzerprofil#Emailversand');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('*map2', 'DE', 'Cachekarte');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('mydetails', 'DE', 'Benutzerprofil#Einstellungen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('myhome', 'DE', 'Benutzerprofil');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('myignores', 'DE', 'Caches ignorieren');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('mylists', 'DE', 'Cachelisten');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('mytop5', 'DE', 'Empfehlungen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('myprofile', 'DE', 'Benutzerprofil#Einstellungen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('mystatpic', 'DE', 'Statistikbild');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('mywatches', 'DE', 'Benachrichtigungen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('newcache', '*', '!articles.php?page=cacheinfo');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('newdesc', 'DE', 'Beschreibungstext');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('newlogpics', 'DE', 'Logbild-Galerien');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('newpw', 'DE', 'Passwort');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('npa', 'DE', 'Schutzgebiete');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('npa', 'EN', 'Protected areas');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('oconly', 'DE', 'OConly');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('oconly81', 'DE', 'OConly-81');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('opencaching', 'DE', 'Opencaching.de');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('opencaching', 'EN', 'About Opencaching.de');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('picture', 'DE', 'Bilder');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('previewpics', 'DE', 'Vorschaubilder');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('query', 'DE', 'Gespeicherte Suchen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('register', 'DE', 'Registrierung');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('register', 'EN', 'Registration');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('removelog_logowner', 'DE', 'Logeintrag löschen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('removelog_cacheowner', 'DE', 'Logeintrag löschen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('reportcache', 'DE', 'Cache melden');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('report_reasons', 'DE', 'Cache melden#Wann melden.3F');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('search', 'DE', 'Suchformular');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('tops', 'DE', 'Empfehlungen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('tops', 'EN', 'Recommendations');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('usernote', 'DE', 'Persönliche Notiz');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('usertops', 'DE', 'Empfehlungen');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('viewcache', 'DE', 'Listing');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('viewlogs', 'DE', 'Das Onlinelog');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('viewprofile', 'DE', 'Benutzerprofil');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('viewprofile_pics', 'DE', 'Logbild-Galerien');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('wikinews', 'DE', 'Hauptseite/Neue Artikel');
INSERT INTO `helppages` (`ocpage`, `language`, `helppage`) VALUES ('wikinews', 'EN', 'New articles');
