-- Table nuts_codes
SET NAMES 'utf8';
TRUNCATE TABLE `nuts_codes`;
INSERT INTO `nuts_codes` (`code`, `name`) VALUES
('AT', 'Österreich'),
('AT1', 'Ostösterreich'),
('AT11', 'Burgenland (A)'),
('AT111', 'Mittelburgenland'),
('AT112', 'Nordburgenland'),
('AT113', 'Südburgenland'),
('AT12', 'Niederösterreich'),
('AT121', 'Mostviertel-Eisenwurzen'),
('AT122', 'Niederösterreich-Süd'),
('AT123', 'Sankt Pölten'),
('AT124', 'Waldviertel'),
('AT125', 'Weinviertel'),
('AT126', 'Wiener Umland/Nordteil'),
('AT127', 'Wiener Umland/Südteil'),
('AT13', 'Wien'),
('AT130', 'Wien'),
('AT2', 'Südösterreich'),
('AT21', 'Kärnten'),
('AT211', 'Klagenfurt-Villach'),
('AT212', 'Oberkärnten'),
('AT213', 'Unterkärnten'),
('AT22', 'Steiermark'),
('AT221', 'Graz'),
('AT222', 'Liezen'),
('AT223', 'Östliche Obersteiermark'),
('AT224', 'Oststeiermark'),
('AT225', 'West- und Südsteiermark'),
('AT226', 'Westliche Obersteiermark'),
('AT3', 'Westösterreich'),
('AT31', 'Oberösterreich'),
('AT311', 'Innviertel'),
('AT312', 'Linz-Wels'),
('AT313', 'Mühlviertel'),
('AT314', 'Steyr-Kirchdorf'),
('AT315', 'Traunviertel'),
('AT32', 'Salzburg'),
('AT321', 'Lungau'),
('AT322', 'Pinzgau-Pongau'),
('AT323', 'Salzburg und Umgebung'),
('AT33', 'Tirol'),
('AT331', 'Außerfern'),
('AT332', 'Innsbruck'),
('AT333', 'Osttirol'),
('AT334', 'Tiroler Oberland'),
('AT335', 'Tiroler Unterland'),
('AT34', 'Vorarlberg'),
('AT341', 'Bludenz-Bregenzer Wald'),
('AT342', 'Rheintal-Bodenseegebiet'),
('ATZ', 'Extra-Regio'),
('ATZZ', 'Extra-Regio'),
('ATZZZ', 'Extra-Regio'),
('BE', 'Belgien'),
('BE1', 'Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest'),
('BE10', 'Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest'),
('BE100', 'Arr. [1] de Bruxelles-Capitale/Arr. van Brussel-Hoofdstad'),
('BE2', 'Vlaams Gewest'),
('BE21', 'Prov. [2] Antwerpen'),
('BE211', 'Arr. Antwerpen'),
('BE212', 'Arr. Mechelen'),
('BE213', 'Arr. Turnhout'),
('BE22', 'Prov. Limburg (B)'),
('BE221', 'Arr. Hasselt'),
('BE222', 'Arr. Maaseik'),
('BE223', 'Arr. Tongeren'),
('BE23', 'Prov. Oost-Vlaanderen'),
('BE231', 'Arr. Aalst'),
('BE232', 'Arr. Dendermonde'),
('BE233', 'Arr. Eeklo'),
('BE234', 'Arr. Gent'),
('BE235', 'Arr. Oudenaarde'),
('BE236', 'Arr. Sint-Niklaas'),
('BE24', 'Prov. Vlaams-Brabant'),
('BE241', 'Arr. Halle-Vilvoorde'),
('BE242', 'Arr. Leuven'),
('BE25', 'Prov. West-Vlaanderen'),
('BE251', 'Arr. Brugge'),
('BE252', 'Arr. Diksmuide'),
('BE253', 'Arr. Ieper'),
('BE254', 'Arr. Kortrijk'),
('BE255', 'Arr. Oostende'),
('BE256', 'Arr. Roeselare'),
('BE257', 'Arr. Tielt'),
('BE258', 'Arr. Veurne'),
('BE3', 'Région Wallonne'),
('BE31', 'Prov. Brabant Wallon'),
('BE310', 'Arr. Nivelles'),
('BE32', 'Prov. Hainaut'),
('BE321', 'Arr. Ath'),
('BE322', 'Arr. Charleroi'),
('BE323', 'Arr. Mons'),
('BE324', 'Arr. Mouscron'),
('BE325', 'Arr. Soignies'),
('BE326', 'Arr. Thuin'),
('BE327', 'Arr. Tournai'),
('BE33', 'Prov. Liège'),
('BE331', 'Arr. Huy'),
('BE332', 'Arr. Liège'),
('BE333', 'Arr. Verviers'),
('BE334', 'Arr. Waremme'),
('BE335', 'Arr. Verviers — communes francophones'),
('BE336', 'Bezirk Verviers — Deutschsprachige Gemeinschaft'),
('BE34', 'Prov. Luxembourg (B)'),
('BE341', 'Arr. Arlon'),
('BE342', 'Arr. Bastogne'),
('BE343', 'Arr. Marche-en-Famenne'),
('BE344', 'Arr. Neufchâteau'),
('BE345', 'Arr. Virton'),
('BE35', 'Prov. Namur'),
('BE351', 'Arr. Dinant'),
('BE352', 'Arr. Namur'),
('BE353', 'Arr. Philippeville'),
('BEZ', 'Extra-Eegio'),
('BEZZ', 'Extra-Regio'),
('BEZZZ', 'Extra-Regio'),
('BG', 'Bulgarien'),
('BG3','Северна и Югоизточна България'),
('BG4','Югозападна и Южна Централна България'),
('BGZ','Extra-Regio'),
('BG31','Северозападен'),
('BG32','Северен централен'),
('BG33','Североизточен'),
('BG34','Югоизточен'),
('BG41','Югозападен'),
('BG42','Южен централен'),
('BGZZ','Extra-Regio'),
('BG311','Видин'),
('BG312','Монтана'),
('BG313','Враца'),
('BG314','Плевен'),
('BG315','Ловеч'),
('BG321','Велико Търново'),
('BG322','Габрово'),
('BG323','Русе'),
('BG324','Разград'),
('BG325','Силистра'),
('BG331','Варна'),
('BG332','Добрич'),
('BG333','Шумен'),
('BG334','Търговище'),
('BG341','Бургас'),
('BG342','Сливен'),
('BG343','Ямбол'),
('BG344','Стара Загора'),
('BG411','София (столица)'),
('BG412','София'),
('BG413','Благоевград'),
('BG414','Перник'),
('BG415','Кюстендил'),
('BG421','Пловдив'),
('BG422','Хасково'),
('BG423','Пазарджик'),
('BG424','Смолян'),
('BG425','Кърджали'),
('BGZZZ','Extra-Regio'),
('CH', 'Schweiz'),
('CH01', 'Région lémanique'),
('CH011', 'Vaud'),
('CH012', 'Valais'),
('CH013', 'Genève'),
('CH02', 'Espace Mittelland'),
('CH021', 'Bern'),
('CH022', 'Freiburg'),
('CH023', 'Solothurn'),
('CH024', 'Neuchâtel'),
('CH025', 'Jura'),
('CH03', 'Nordwestschweiz'),
('CH031', 'Basel-Stadt'),
('CH032', 'Basel-Landschaft'),
('CH033', 'Aargau'),
('CH04', 'Zürich'),
('CH05', 'Ostschweiz'),
('CH051', 'Glarus'),
('CH052', 'Schaffhausen'),
('CH053', 'Appenzell Ausserrhoden'),
('CH054', 'Appenzell Innerrhoden'),
('CH055', 'St. Gallen'),
('CH056', 'Graubünden'),
('CH057', 'Thurgau'),
('CH06', 'Zentralschweiz'),
('CH061', 'Luzern'),
('CH062', 'Uri'),
('CH063', 'Schwyz'),
('CH064', 'Obwalden'),
('CH065', 'Nidwalden'),
('CH066', 'Zug'),
('CH07', 'Ticino'),
('CY', 'Zypern'),
('CY0', 'Κύπρος/Kıbrıs'),
('CY00', 'Κύπρος/Kıbrıs'),
('CY000', 'Κύπρος/Kıbrıs'),
('CYZ', 'Extra-Regio'),
('CYZZ', 'Extra-Regio'),
('CYZZZ', 'Extra-Regio'),
('CZ', 'Tschechische Republik'),
('CZ0', 'Česká republika'),
('CZ01', 'Praha'),
('CZ010', 'Hlavní město Praha'),
('CZ02', 'Střední Čechy'),
('CZ020', 'Středočeský kraj'),
('CZ03', 'Jihozápad'),
('CZ031', 'Jihočeský kraj'),
('CZ032', 'Plzeňský kraj'),
('CZ04', 'Severozápad'),
('CZ041', 'Karlovarský kraj'),
('CZ042', 'Ústecký kraj'),
('CZ05', 'Severovýchod'),
('CZ051', 'Liberecký kraj'),
('CZ052', 'Královéhradecký kraj'),
('CZ053', 'Pardubický kraj'),
('CZ06', 'Jihovýchod'),
('CZ061', 'Kraj Vysočina'),
('CZ062', 'Jihomoravský kraj'),
('CZ063', 'Vysočina'),
('CZ064', 'Jihomoravský kraj'),
('CZ07', 'Střední Morava'),
('CZ071', 'Olomoucký kraj'),
('CZ072', 'Zlínský kraj'),
('CZ08', 'Moravskoslezsko'),
('CZ080', 'Moravskoslezský kraj'),
('CZZ', 'Extra-Regio'),
('CZZZ', 'Extra-Regio'),
('CZZZZ', 'Extra-Regio'),
('DE', 'Deutschland'),
('DE1', 'Baden-Württemberg'),
('DE11', 'Stuttgart'),
('DE111', 'Stuttgart, Stadtkreis'),
('DE112', 'Böblingen'),
('DE113', 'Esslingen'),
('DE114', 'Göppingen'),
('DE115', 'Ludwigsburg'),
('DE116', 'Rems-Murr-Kreis'),
('DE117', 'Heilbronn, Stadtkreis'),
('DE118', 'Heilbronn, Landkreis'),
('DE119', 'Hohenlohekreis'),
('DE11A', 'Schwäbisch Hall'),
('DE11B', 'Main-Tauber-Kreis'),
('DE11C', 'Heidenheim'),
('DE11D', 'Ostalbkreis'),
('DE12', 'Karlsruhe'),
('DE121', 'Baden-Baden, Stadtkreis'),
('DE122', 'Karlsruhe, Stadtkreis'),
('DE123', 'Karlsruhe, Landkreis'),
('DE124', 'Rastatt'),
('DE125', 'Heidelberg, Stadtkreis'),
('DE126', 'Mannheim, Stadtkreis'),
('DE127', 'Neckar-Odenwald-Kreis'),
('DE128', 'Rhein-Neckar-Kreis'),
('DE129', 'Pforzheim, Stadtkreis'),
('DE12A', 'Calw'),
('DE12B', 'Enzkreis'),
('DE12C', 'Freudenstadt'),
('DE13', 'Freiburg'),
('DE131', 'Freiburg im Breisgau, Stadtkreis'),
('DE132', 'Breisgau-Hochschwarzwald'),
('DE133', 'Emmendingen'),
('DE134', 'Ortenaukreis'),
('DE135', 'Rottweil'),
('DE136', 'Schwarzwald-Baar-Kreis'),
('DE137', 'Tuttlingen'),
('DE138', 'Konstanz'),
('DE139', 'Lörrach'),
('DE13A', 'Waldshut'),
('DE14', 'Tübingen'),
('DE141', 'Reutlingen'),
('DE142', 'Tübingen, Landkreis'),
('DE143', 'Zollernalbkreis'),
('DE144', 'Ulm, Stadtkreis'),
('DE145', 'Alb-Donau-Kreis'),
('DE146', 'Biberach'),
('DE147', 'Bodenseekreis'),
('DE148', 'Ravensburg'),
('DE149', 'Sigmaringen'),
('DE2', 'Bayern'),
('DE21', 'Oberbayern'),
('DE211', 'Ingolstadt, Kreisfreie Stadt'),
('DE212', 'München, Kreisfreie Stadt'),
('DE213', 'Rosenheim, Kreisfreie Stadt'),
('DE214', 'Altötting'),
('DE215', 'Berchtesgadener Land'),
('DE216', 'Bad Tölz-Wolfratshausen'),
('DE217', 'Dachau'),
('DE218', 'Ebersberg'),
('DE219', 'Eichstätt'),
('DE21A', 'Erding'),
('DE21B', 'Freising'),
('DE21C', 'Fürstenfeldbruck'),
('DE21D', 'Garmisch-Partenkirchen'),
('DE21E', 'Landsberg a. Lech'),
('DE21F', 'Miesbach'),
('DE21G', 'Mühldorf a. Inn'),
('DE21H', 'München, Landkreis'),
('DE21I', 'Neuburg-Schrobenhausen'),
('DE21J', 'Pfaffenhofen a. d. Ilm'),
('DE21K', 'Rosenheim, Landkreis'),
('DE21L', 'Starnberg'),
('DE21M', 'Traunstein'),
('DE21N', 'Weilheim-Schongau'),
('DE22', 'Niederbayern'),
('DE221', 'Landshut, Kreisfreie Stadt'),
('DE222', 'Passau, Kreisfreie Stadt'),
('DE223', 'Straubing, Kreisfreie Stadt'),
('DE224', 'Deggendorf'),
('DE225', 'Freyung-Grafenau'),
('DE226', 'Kelheim'),
('DE227', 'Landshut, Landkreis'),
('DE228', 'Passau, Landkreis'),
('DE229', 'Regen'),
('DE22A', 'Rottal-Inn'),
('DE22B', 'Straubing-Bogen'),
('DE22C', 'Dingolfing-Landau'),
('DE23', 'Oberpfalz'),
('DE231', 'Amberg, Kreisfreie Stadt'),
('DE232', 'Regensburg, Kreisfreie Stadt'),
('DE233', 'Weiden i. d. Opf, Kreisfreie Stadt'),
('DE234', 'Amberg-Sulzbach'),
('DE235', 'Cham'),
('DE236', 'Neumarkt i. d. OPf.'),
('DE237', 'Neustadt a. d. Waldnaab'),
('DE238', 'Regensburg, Landkreis'),
('DE239', 'Schwandorf'),
('DE23A', 'Tirschenreuth'),
('DE24', 'Oberfranken'),
('DE241', 'Bamberg, Kreisfreie Stadt'),
('DE242', 'Bayreuth, Kreisfreie Stadt'),
('DE243', 'Coburg, Kreisfreie Stadt'),
('DE244', 'Hof, Kreisfreie Stadt'),
('DE245', 'Bamberg, Landkreis'),
('DE246', 'Bayreuth, Landkreis'),
('DE247', 'Coburg, Landkreis'),
('DE248', 'Forchheim'),
('DE249', 'Hof, Landkreis'),
('DE24A', 'Kronach'),
('DE24B', 'Kulmbach'),
('DE24C', 'Lichtenfels'),
('DE24D', 'Wunsiedel i. Fichtelgebirge'),
('DE25', 'Mittelfranken'),
('DE251', 'Ansbach, Kreisfreie Stadt'),
('DE252', 'Erlangen, Kreisfreie Stadt'),
('DE253', 'Fürth, Kreisfreie Stadt'),
('DE254', 'Nürnberg, Kreisfreie Stadt'),
('DE255', 'Schwabach, Kreisfreie Stadt'),
('DE256', 'Ansbach, Landkreis'),
('DE257', 'Erlangen-Höchstadt'),
('DE258', 'Fürth, Landkreis'),
('DE259', 'Nürnberger Land'),
('DE25A', 'Neustadt a. d. Aisch-Bad Windsheim'),
('DE25B', 'Roth'),
('DE25C', 'Weißenburg-Gunzenhausen'),
('DE26', 'Unterfranken'),
('DE261', 'Aschaffenburg, Kreisfreie Stadt'),
('DE262', 'Schweinfurt, Kreisfreie Stadt'),
('DE263', 'Würzburg, Kreisfreie Stadt'),
('DE264', 'Aschaffenburg, Landkreis'),
('DE265', 'Bad Kissingen'),
('DE266', 'Rhön-Grabfeld'),
('DE267', 'Haßberge'),
('DE268', 'Kitzingen'),
('DE269', 'Miltenberg'),
('DE26A', 'Main-Spessart'),
('DE26B', 'Schweinfurt, Landkreis'),
('DE26C', 'Würzburg, Landkreis'),
('DE27', 'Schwaben'),
('DE271', 'Augsburg, Kreisfreie Stadt'),
('DE272', 'Kaufbeuren, Kreisfreie Stadt'),
('DE273', 'Kempten (Allgäu), Kreisfreie Stadt'),
('DE274', 'Memmingen, Kreisfreie Stadt'),
('DE275', 'Aichach-Friedberg'),
('DE276', 'Augsburg, Landkreis'),
('DE277', 'Dillingen a.d. Donau'),
('DE278', 'Günzburg'),
('DE279', 'Neu-Ulm'),
('DE27A', 'Lindau (Bodensee)'),
('DE27B', 'Ostallgäu'),
('DE27C', 'Unterallgäu'),
('DE27D', 'Donau-Ries'),
('DE27E', 'Oberallgäu'),
('DE3', 'Berlin'),
('DE30', 'Berlin'),
('DE300', 'Berlin'),
('DE4', 'Brandenburg'),
('DE41', 'Brandenburg — Nordost'),
('DE411', 'Frankfurt (Oder), Kreisfreie Stadt'),
('DE412', 'Barnim'),
('DE413', 'Märkisch-Oderland'),
('DE414', 'Oberhavel'),
('DE415', 'Oder-Spree'),
('DE416', 'Ostprignitz-Ruppin'),
('DE417', 'Prignitz'),
('DE418', 'Uckermark'),
('DE42', 'Brandenburg — Südwest'),
('DE421', 'Brandenburg an der Havel, Kreisfreie Stadt'),
('DE422', 'Cottbus, Kreisfreie Stadt'),
('DE423', 'Potsdam, Kreisfreie Stadt'),
('DE424', 'Dahme-Spreewald'),
('DE425', 'Elbe-Elster'),
('DE426', 'Havelland'),
('DE427', 'Oberspreewald-Lausitz'),
('DE428', 'Potsdam-Mittelmark'),
('DE429', 'Spree-Neiße'),
('DE42A', 'Teltow-Fläming'),
('DE5', 'Bremen'),
('DE50', 'Bremen'),
('DE501', 'Bremen, Kreisfreie Stadt'),
('DE502', 'Bremerhaven, Kreisfreie Stadt'),
('DE6', 'Hamburg'),
('DE60', 'Hamburg'),
('DE600', 'Hamburg'),
('DE7', 'Hessen'),
('DE71', 'Darmstadt'),
('DE711', 'Darmstadt, Kreisfreie Stadt'),
('DE712', 'Frankfurt am Main, Kreisfreie Stadt'),
('DE713', 'Offenbach am Main, Kreisfreie Stadt'),
('DE714', 'Wiesbaden, Kreisfreie Stadt'),
('DE715', 'Bergstraße'),
('DE716', 'Darmstadt-Dieburg'),
('DE717', 'Groß-Gerau'),
('DE718', 'Hochtaunuskreis'),
('DE719', 'Main-Kinzig-Kreis'),
('DE71A', 'Main-Taunus-Kreis'),
('DE71B', 'Odenwaldkreis'),
('DE71C', 'Offenbach, Landkreis'),
('DE71D', 'Rheingau-Taunus-Kreis'),
('DE71E', 'Wetteraukreis'),
('DE72', 'Gießen'),
('DE721', 'Gießen, Landkreis'),
('DE722', 'Lahn-Dill-Kreis'),
('DE723', 'Limburg-Weilburg'),
('DE724', 'Marburg-Biedenkopf'),
('DE725', 'Vogelsbergkreis'),
('DE73', 'Kassel'),
('DE731', 'Kassel, Kreisfreie Stadt'),
('DE732', 'Fulda'),
('DE733', 'Hersfeld-Rotenburg'),
('DE734', 'Kassel, Landkreis'),
('DE735', 'Schwalm-Eder-Kreis'),
('DE736', 'Waldeck-Frankenberg'),
('DE737', 'Werra-Meißner-Kreis'),
('DE8', 'Mecklenburg-Vorpommern'),
('DE80', 'Mecklenburg-Vorpommern'),
('DE801', 'Greifswald, Kreisfreie Stadt'),
('DE802', 'Neubrandenburg, Kreisfreie Stadt'),
('DE803', 'Rostock, Kreisfreie Stadt'),
('DE804', 'Schwerin, Kreisfreie Stadt'),
('DE805', 'Stralsund, Kreisfreie Stadt'),
('DE806', 'Wismar, Kreisfreie Stadt'),
('DE807', 'Bad Doberan'),
('DE808', 'Demmin'),
('DE809', 'Güstrow'),
('DE80A', 'Ludwigslust'),
('DE80B', 'Mecklenburg-Strelitz'),
('DE80C', 'Müritz'),
('DE80D', 'Nordvorpommern'),
('DE80E', 'Nordwestmecklenburg'),
('DE80F', 'Ostvorpommern'),
('DE80G', 'Parchim'),
('DE80H', 'Rügen'),
('DE80I', 'Uecker-Randow'),
('DE9', 'Niedersachsen'),
('DE91', 'Braunschweig'),
('DE911', 'Braunschweig, Kreisfreie Stadt'),
('DE912', 'Salzgitter, Kreisfreie Stadt'),
('DE913', 'Wolfsburg, Kreisfreie Stadt'),
('DE914', 'Gifhorn'),
('DE915', 'Göttingen'),
('DE916', 'Goslar'),
('DE917', 'Helmstedt'),
('DE918', 'Northeim'),
('DE919', 'Osterode am Harz'),
('DE91A', 'Peine'),
('DE91B', 'Wolfenbüttel'),
('DE92', 'Hannover'),
('DE922', 'Diepholz'),
('DE923', 'Hameln-Pyrmont'),
('DE925', 'Hildesheim'),
('DE926', 'Holzminden'),
('DE927', 'Nienburg (Weser)'),
('DE928', 'Schaumburg'),
('DE929', 'Region Hannover'),
('DE93', 'Lüneburg'),
('DE931', 'Celle'),
('DE932', 'Cuxhaven'),
('DE933', 'Harburg'),
('DE934', 'Lüchow-Dannenberg'),
('DE935', 'Lüneburg, Landkreis'),
('DE936', 'Osterholz'),
('DE937', 'Rotenburg (Wümme)'),
('DE938', 'Soltau-Fallingbostel'),
('DE939', 'Stade'),
('DE93A', 'Uelzen'),
('DE93B', 'Verden'),
('DE94', 'Weser-Ems'),
('DE941', 'Delmenhorst, Kreisfreie Stadt'),
('DE942', 'Emden, Kreisfreie Stadt'),
('DE943', 'Oldenburg (Oldenburg), Kreisfreie Stadt'),
('DE944', 'Osnabrück, Kreisfreie Stadt'),
('DE945', 'Wilhelmshaven, Kreisfreie Stadt'),
('DE946', 'Ammerland'),
('DE947', 'Aurich'),
('DE948', 'Cloppenburg'),
('DE949', 'Emsland'),
('DE94A', 'Friesland (D)'),
('DE94B', 'Grafschaft Bentheim'),
('DE94C', 'Leer'),
('DE94D', 'Oldenburg, Landkreis'),
('DE94E', 'Osnabrück, Landkreis'),
('DE94F', 'Vechta'),
('DE94G', 'Wesermarsch'),
('DE94H', 'Wittmund'),
('DEA', 'Nordrhein-Westfalen'),
('DEA1', 'Düsseldorf'),
('DEA11', 'Düsseldorf, Kreisfreie Stadt'),
('DEA12', 'Duisburg, Kreisfreie Stadt'),
('DEA13', 'Essen, Kreisfreie Stadt'),
('DEA14', 'Krefeld, Kreisfreie Stadt'),
('DEA15', 'Mönchengladbach, Kreisfreie Stadt'),
('DEA16', 'Mülheim an der Ruhr, Kreisfreie Stadt'),
('DEA17', 'Oberhausen, Kreisfreie Stadt'),
('DEA18', 'Remscheid, Kreisfreie Stadt'),
('DEA19', 'Solingen, Kreisfreie Stadt'),
('DEA1A', 'Wuppertal, Kreisfreie Stadt'),
('DEA1B', 'Kleve'),
('DEA1C', 'Mettmann'),
('DEA1D', 'Rhein-Kreis Neuss'),
('DEA1E', 'Viersen'),
('DEA1F', 'Wesel'),
('DEA2', 'Köln'),
('DEA21', 'Aachen, Kreisfreie Stadt'),
('DEA22', 'Bonn, Kreisfreie Stadt'),
('DEA23', 'Köln, Kreisfreie Stadt'),
('DEA24', 'Leverkusen, Kreisfreie Stadt'),
('DEA25', 'Aachen, Kreis'),
('DEA26', 'Düren'),
('DEA27', 'Rhein-Erft-Kreis'),
('DEA28', 'Euskirchen'),
('DEA29', 'Heinsberg'),
('DEA2A', 'Oberbergischer Kreis'),
('DEA2B', 'Rheinisch-Bergischer Kreis'),
('DEA2C', 'Rhein-Sieg-Kreis'),
('DEA3', 'Münster'),
('DEA31', 'Bottrop, Kreisfreie Stadt'),
('DEA32', 'Gelsenkirchen, Kreisfreie Stadt'),
('DEA33', 'Münster, Kreisfreie Stadt'),
('DEA34', 'Borken'),
('DEA35', 'Coesfeld'),
('DEA36', 'Recklinghausen'),
('DEA37', 'Steinfurt'),
('DEA38', 'Warendorf'),
('DEA4', 'Detmold'),
('DEA41', 'Bielefeld, Kreisfreie Stadt'),
('DEA42', 'Gütersloh'),
('DEA43', 'Herford'),
('DEA44', 'Höxter'),
('DEA45', 'Lippe'),
('DEA46', 'Minden-Lübbecke'),
('DEA47', 'Paderborn'),
('DEA5', 'Arnsberg'),
('DEA51', 'Bochum, Kreisfreie Stadt'),
('DEA52', 'Dortmund, Kreisfreie Stadt'),
('DEA53', 'Hagen, Kreisfreie Stadt'),
('DEA54', 'Hamm, Kreisfreie Stadt'),
('DEA55', 'Herne, Kreisfreie Stadt'),
('DEA56', 'Ennepe-Ruhr-Kreis'),
('DEA57', 'Hochsauerlandkreis'),
('DEA58', 'Märkischer Kreis'),
('DEA59', 'Olpe'),
('DEA5A', 'Siegen-Wittgenstein'),
('DEA5B', 'Soest'),
('DEA5C', 'Unna'),
('DEB', 'Rheinland-Pfalz'),
('DEB1', 'Koblenz'),
('DEB11', 'Koblenz, Kreisfreie Stadt'),
('DEB12', 'Ahrweiler'),
('DEB13', 'Altenkirchen (Westerwald)'),
('DEB14', 'Bad Kreuznach'),
('DEB15', 'Birkenfeld'),
('DEB16', 'Cochem-Zell'),
('DEB17', 'Mayen-Koblenz'),
('DEB18', 'Neuwied'),
('DEB19', 'Rhein-Hunsrück-Kreis'),
('DEB1A', 'Rhein-Lahn-Kreis'),
('DEB1B', 'Westerwaldkreis'),
('DEB2', 'Trier'),
('DEB21', 'Trier, Kreisfreie Stadt'),
('DEB22', 'Bernkastel-Wittlich'),
('DEB23', 'Bitburg-Prüm'),
('DEB24', 'Daun'),
('DEB25', 'Trier-Saarburg'),
('DEB3', 'Rheinhessen-Pfalz'),
('DEB31', 'Frankenthal (Pfalz), Kreisfreie Stadt'),
('DEB32', 'Kaiserslautern, Kreisfreie Stadt'),
('DEB33', 'Landau in der Pfalz, Kreisfreie Stadt'),
('DEB34', 'Ludwigshafen am Rhein, Kreisfreie Stadt'),
('DEB35', 'Mainz, Kreisfreie Stadt'),
('DEB36', 'Neustadt an der Weinstraße, Kreisfreie Stadt'),
('DEB37', 'Pirmasens, Kreisfreie Stadt'),
('DEB38', 'Speyer, Kreisfreie Stadt'),
('DEB39', 'Worms, Kreisfreie Stadt'),
('DEB3A', 'Zweibrücken, Kreisfreie Stadt'),
('DEB3B', 'Alzey-Worms'),
('DEB3C', 'Bad Dürkheim'),
('DEB3D', 'Donnersbergkreis'),
('DEB3E', 'Germersheim'),
('DEB3F', 'Kaiserslautern, Landkreis'),
('DEB3G', 'Kusel'),
('DEB3H', 'Südliche Weinstraße'),
('DEB3I', 'Rhein-Pfalz-Kreis'),
('DEB3J', 'Mainz-Bingen'),
('DEB3K', 'Südwestpfalz'),
('DEC', 'Saarland'),
('DEC0', 'Saarland'),
('DEC01', 'Stadtverband Saarbrücken'),
('DEC02', 'Merzig-Wadern'),
('DEC03', 'Neunkirchen'),
('DEC04', 'Saarlouis'),
('DEC05', 'Saarpfalz-Kreis'),
('DEC06', 'St. Wendel'),
('DED', 'Sachsen'),
('DED1', 'Chemnitz'),
('DED11', 'Chemnitz, Kreisfreie Stadt'),
('DED12', 'Plauen, Kreisfreie Stadt'),
('DED13', 'Zwickau, Kreisfreie Stadt'),
('DED14', 'Annaberg'),
('DED15', 'Chemnitzer Land'),
('DED16', 'Freiberg'),
('DED17', 'Vogtlandkreis'),
('DED18', 'Mittlerer Erzgebirgskreis'),
('DED19', 'Mittweida'),
('DED1A', 'Stollberg'),
('DED1B', 'Aue-Schwarzenberg'),
('DED1C', 'Zwickauer Land'),
('DED2', 'Dresden'),
('DED21', 'Dresden, Kreisfreie Stadt'),
('DED22', 'Görlitz, Kreisfreie Stadt'),
('DED23', 'Hoyerswerda, Kreisfreie Stadt'),
('DED24', 'Bautzen'),
('DED25', 'Meißen'),
('DED26', 'Niederschlesischer Oberlausitzkreis'),
('DED27', 'Riesa-Großenhain'),
('DED28', 'Löbau-Zittau'),
('DED29', 'Sächsische Schweiz'),
('DED2A', 'Weißeritzkreis'),
('DED2B', 'Kamenz'),
('DED3', 'Leipzig'),
('DED31', 'Leipzig, Kreisfreie Stadt'),
('DED32', 'Delitzsch'),
('DED33', 'Döbeln'),
('DED34', 'Leipziger Land'),
('DED35', 'Muldentalkreis'),
('DED36', 'Torgau-Oschatz'),
('DEE', 'Sachsen-Anhalt'),
('DEE0', 'Sachsen-Anhalt'),
('DEE01', 'Dessau-Roßlau, Kreisfreie Stadt'),
('DEE02', 'Halle (Saale), Kreisfreie Stadt'),
('DEE03', 'Magdeburg, Kreisfreie Stadt'),
('DEE04', 'Altmarkkreis Salzwedel'),
('DEE05', 'Anhalt-Bitterfeld'),
('DEE06', 'Jerichower Land'),
('DEE07', 'Börde'),
('DEE08', 'Burgenland (D)'),
('DEE09', 'Harz'),
('DEE0A', 'Mansfeld-Südharz'),
('DEE0B', 'Saalekreis'),
('DEE0C', 'Salzland'),
('DEE0D', 'Stendal'),
('DEE0E', 'Wittenberg'),
('DEE1', 'Dessau'),
('DEE11', 'Dessau, Krfr. St.'),
('DEE12', 'Anhalt-Zerbst'),
('DEE13', 'Bernburg'),
('DEE14', 'Bitterfeld'),
('DEE15', 'Köthen'),
('DEE16', 'Wittenberg'),
('DEE2', 'Halle'),
('DEE21', 'Halle/Saale, Stadtkr.'),
('DEE22', 'Burgenlandkreis'),
('DEE23', 'Mansfelder Land'),
('DEE24', 'Merseburg-Querfurt'),
('DEE25', 'Saalkreis'),
('DEE26', 'Sangerhausen'),
('DEE27', 'Weissenfels'),
('DEE3', 'Magdeburg'),
('DEE31', 'Magdeburg, Krfr. St.'),
('DEE32', 'Aschersleben-Stassfurt'),
('DEE33', 'Boerdekreis'),
('DEE34', 'Halberstadt'),
('DEE35', 'Jerichower Land'),
('DEE36', 'Ohrekreis'),
('DEE37', 'Stendal'),
('DEE38', 'Quedlinburg'),
('DEE39', 'Schoenebeck'),
('DEE3A', 'Wernigerode'),
('DEE3B', 'Altmarkkreis Salzwedel'),
('DEF', 'Schleswig-Holstein'),
('DEF0', 'Schleswig-Holstein'),
('DEF01', 'Flensburg, Kreisfreie Stadt'),
('DEF02', 'Kiel, Kreisfreie Stadt'),
('DEF03', 'Lübeck, Kreisfreie Stadt'),
('DEF04', 'Neumünster, Kreisfreie Stadt'),
('DEF05', 'Dithmarschen'),
('DEF06', 'Herzogtum Lauenburg'),
('DEF07', 'Nordfriesland'),
('DEF08', 'Ostholstein'),
('DEF09', 'Pinneberg'),
('DEF0A', 'Plön'),
('DEF0B', 'Rendsburg-Eckernförde'),
('DEF0C', 'Schleswig-Flensburg'),
('DEF0D', 'Segeberg'),
('DEF0E', 'Steinburg'),
('DEF0F', 'Stormarn'),
('DEG', 'Thüringen'),
('DEG0', 'Thüringen'),
('DEG01', 'Erfurt, Kreisfreie Stadt'),
('DEG02', 'Gera, Kreisfreie Stadt'),
('DEG03', 'Jena, Kreisfreie Stadt'),
('DEG04', 'Suhl, Kreisfreie Stadt'),
('DEG05', 'Weimar, Kreisfreie Stadt'),
('DEG06', 'Eichsfeld'),
('DEG07', 'Nordhausen'),
('DEG09', 'Unstrut-Hainich-Kreis'),
('DEG0A', 'Kyffhäuserkreis'),
('DEG0B', 'Schmalkalden-Meiningen'),
('DEG0C', 'Gotha'),
('DEG0D', 'Sömmerda'),
('DEG0E', 'Hildburghausen'),
('DEG0F', 'Ilm-Kreis'),
('DEG0G', 'Weimarer Land'),
('DEG0H', 'Sonneberg'),
('DEG0I', 'Saalfeld-Rudolstadt'),
('DEG0J', 'Saale-Holzland-Kreis'),
('DEG0K', 'Saale-Orla-Kreis'),
('DEG0L', 'Greiz'),
('DEG0M', 'Altenburger Land'),
('DEG0N', 'Eisenach, Kreisfreie Stadt'),
('DEG0P', 'Wartburgkreis'),
('DEZ', 'Extra-Regio'),
('DEZZ', 'Extra-Regio'),
('DEZZZ', 'Extra-Regio'),
('DK', 'Dänemark'),
('DK01', 'Hovedstaden'),
('DK011', 'Byen København'),
('DK012', 'Københavns omegn'),
('DK013', 'Nordsjælland'),
('DK014', 'Bornholm'),
('DK02', 'Sjælland'),
('DK021', 'Østsjælland'),
('DK022', 'Vest- og Sydsjælland'),
('DK03', 'Syddanmark'),
('DK031', 'Fyn'),
('DK032', 'Sydjylland'),
('DK04', 'Midtjylland'),
('DK041', 'Vestjylland'),
('DK042', 'Østjylland'),
('DK05', 'Nordjylland'),
('DK050', 'Nordjylland'),
('DKZ', 'Extra-Regio'),
('DKZZ', 'Extra-Regio'),
('DKZZZ', 'Extra-Regio'),
('EE', 'Estland'),
('EE0', 'Eesti'),
('EE00', 'Eesti'),
('EE001', 'Põhja-Eesti'),
('EE004', 'Lääne-Eesti'),
('EE006', 'Kesk-Eesti'),
('EE007', 'Kirde-Eesti'),
('EE008', 'Lõuna-Eesti'),
('EEZ', 'Extra-Regio'),
('EEZZ', 'Extra-Regio'),
('EEZZZ', 'Extra-Regio'),
('ES', 'Spanien'),
('ES1', 'Noroeste'),
('ES11', 'Galicia'),
('ES111', 'A Coruña'),
('ES112', 'Lugo'),
('ES113', 'Ourense'),
('ES114', 'Pontevedra'),
('ES12', 'Principado de Asturias'),
('ES120', 'Asturias'),
('ES13', 'Cantabria'),
('ES130', 'Cantabria'),
('ES2', 'Noreste'),
('ES21', 'País Vasco'),
('ES211', 'Álava'),
('ES212', 'Guipúzcoa'),
('ES213', 'Vizcaya'),
('ES22', 'Comunidad Foral de Navarra'),
('ES220', 'Navarra'),
('ES23', 'La Rioja'),
('ES230', 'La Rioja'),
('ES24', 'Aragón'),
('ES241', 'Huesca'),
('ES242', 'Teruel'),
('ES243', 'Zaragoza'),
('ES3', 'Comunidad de Madrid'),
('ES30', 'Comunidad de Madrid'),
('ES300', 'Madrid'),
('ES4', 'Centro (e)'),
('ES41', 'Castilla y León'),
('ES411', 'Ávila'),
('ES412', 'Burgos'),
('ES413', 'León'),
('ES414', 'Palencia'),
('ES415', 'Salamanca'),
('ES416', 'Segovia'),
('ES417', 'Soria'),
('ES418', 'Valladolid'),
('ES419', 'Zamora'),
('ES42', 'Castilla-La Mancha'),
('ES421', 'Albacete'),
('ES422', 'Ciudad Real'),
('ES423', 'Cuenca'),
('ES424', 'Guadalajara'),
('ES425', 'Toledo'),
('ES43', 'Extremadura'),
('ES431', 'Badajoz'),
('ES432', 'Cáceres'),
('ES5', 'Este'),
('ES51', 'Cataluña'),
('ES511', 'Barcelona'),
('ES512', 'Girona'),
('ES513', 'Lleida'),
('ES514', 'Tarragona'),
('ES52', 'Comunidad Valenciana'),
('ES521', 'Alicante/Alacant'),
('ES522', 'Castellón/Castelló'),
('ES523', 'Valencia/València'),
('ES53', 'Illes Balears'),
('ES531', 'Eivissa y Formentera'),
('ES532', 'Mallorca'),
('ES533', 'Menorca'),
('ES6', 'Sur'),
('ES61', 'Andalucía'),
('ES611', 'Almería'),
('ES612', 'Cádiz'),
('ES613', 'Córdoba'),
('ES614', 'Granada'),
('ES615', 'Huelva'),
('ES616', 'Jaén'),
('ES617', 'Málaga'),
('ES618', 'Sevilla'),
('ES62', 'Región de Murcia'),
('ES620', 'Murcia'),
('ES63', 'Ciudad Autónoma de Ceuta'),
('ES630', 'Ceuta'),
('ES64', 'Ciudad Autónoma de Melilla'),
('ES640', 'Melilla'),
('ES7', 'Canarias'),
('ES70', 'Canarias'),
('ES703', 'El Hierro'),
('ES704', 'Fuerteventura'),
('ES705', 'Gran Canaria'),
('ES706', 'La Gomera'),
('ES707', 'La Palma'),
('ES708', 'Lanzarote'),
('ES709', 'Tenerife'),
('ESZ', 'Extra-Regio'),
('ESZZ', 'Extra-Regio'),
('ESZZZ', 'Extra-Regio'),
('FI', 'Finnland'),
('FI1', 'Manner-Suomi'),
('FI13', 'Itä-Suomi'),
('FI131', 'Etelä-Savo'),
('FI132', 'Pohjois-Savo'),
('FI133', 'Pohjois-Karjala'),
('FI134', 'Kainuu'),
('FI18', 'Etelä-Suomi'),
('FI181', 'Uusimaa'),
('FI182', 'Itä-Uusimaa'),
('FI183', 'Varsinais-Suomi'),
('FI184', 'Kanta-Häme'),
('FI185', 'Päijät-Häme'),
('FI186', 'Kymenlaakso'),
('FI187', 'Etelä-Karjala'),
('FI19', 'Länsi-Suomi'),
('FI193', 'Keski-Suomi'),
('FI194', 'Etelä-Pohjanmaa'),
('FI195', 'Pohjanmaa'),
('FI196', 'Satakunta'),
('FI197', 'Pirkanmaa'),
('FI1A', 'Pohjois-Suomi'),
('FI1A1', 'Keski-Pohjanmaa'),
('FI1A2', 'Pohjois-Pohjanmaa'),
('FI1A3', 'Lappi'),
('FI2', 'Åland'),
('FI20', 'Åland'),
('FI200', 'Åland'),
('FIZ', 'Extra-Regio'),
('FIZZ', 'Extra-Regio'),
('FIZZZ', 'Extra-Regio'),
('FR', 'Frankreich'),
('FR1', 'Île de France'),
('FR10', 'Île de France'),
('FR101', 'Paris'),
('FR102', 'Seine-et-Marne'),
('FR103', 'Yvelines'),
('FR104', 'Essonne'),
('FR105', 'Hauts-de-Seine'),
('FR106', 'Seine-Saint-Denis'),
('FR107', 'Val-de-Marne'),
('FR108', 'Val-d''Oise'),
('FR2', 'Bassin Parisien'),
('FR21', 'Champagne-Ardenne'),
('FR211', 'Ardennes'),
('FR212', 'Aube'),
('FR213', 'Marne'),
('FR214', 'Haute-Marne'),
('FR22', 'Picardie'),
('FR221', 'Aisne'),
('FR222', 'Oise'),
('FR223', 'Somme'),
('FR23', 'Haute-Normandie'),
('FR231', 'Eure'),
('FR232', 'Seine-Maritime'),
('FR24', 'Centre'),
('FR241', 'Cher'),
('FR242', 'Eure-et-Loir'),
('FR243', 'Indre'),
('FR244', 'Indre-et-Loire'),
('FR245', 'Loir-et-Cher'),
('FR246', 'Loiret'),
('FR25', 'Basse-Normandie'),
('FR251', 'Calvados'),
('FR252', 'Manche'),
('FR253', 'Orne'),
('FR26', 'Bourgogne'),
('FR261', 'Côte-d''Or'),
('FR262', 'Nièvre'),
('FR263', 'Saône-et-Loire'),
('FR264', 'Yonne'),
('FR3', 'Nord — Pas-de-Calais'),
('FR30', 'Nord — Pas-de-Calais'),
('FR301', 'Nord'),
('FR302', 'Pas-de-Calais'),
('FR4', 'Est'),
('FR41', 'Lorraine'),
('FR411', 'Meurthe-et-Moselle'),
('FR412', 'Meuse'),
('FR413', 'Moselle'),
('FR414', 'Vosges'),
('FR42', 'Alsace'),
('FR421', 'Bas-Rhin'),
('FR422', 'Haut-Rhin'),
('FR43', 'Franche-Comté'),
('FR431', 'Doubs'),
('FR432', 'Jura'),
('FR433', 'Haute-Saône'),
('FR434', 'Territoire de Belfort'),
('FR5', 'Ouest'),
('FR51', 'Pays de la Loire'),
('FR511', 'Loire-Atlantique'),
('FR512', 'Maine-et-Loire'),
('FR513', 'Mayenne'),
('FR514', 'Sarthe'),
('FR515', 'Vendée'),
('FR52', 'Bretagne'),
('FR521', 'Côtes-d''Armor'),
('FR522', 'Finistère'),
('FR523', 'Ille-et-Vilaine'),
('FR524', 'Morbihan'),
('FR53', 'Poitou-Charentes'),
('FR531', 'Charente'),
('FR532', 'Charente-Maritime'),
('FR533', 'Deux-Sèvres'),
('FR534', 'Vienne'),
('FR6', 'Sud-Ouest'),
('FR61', 'Aquitaine'),
('FR611', 'Dordogne'),
('FR612', 'Gironde'),
('FR613', 'Landes'),
('FR614', 'Lot-et-Garonne'),
('FR615', 'Pyrénées-Atlantiques'),
('FR62', 'Midi-Pyrénées'),
('FR621', 'Ariège'),
('FR622', 'Aveyron'),
('FR623', 'Haute-Garonne'),
('FR624', 'Gers'),
('FR625', 'Lot'),
('FR626', 'Hautes-Pyrénées'),
('FR627', 'Tarn'),
('FR628', 'Tarn-et-Garonne'),
('FR63', 'Limousin'),
('FR631', 'Corrèze'),
('FR632', 'Creuse'),
('FR633', 'Haute-Vienne'),
('FR7', 'Centre-Est'),
('FR71', 'Rhône-Alpes'),
('FR711', 'Ain'),
('FR712', 'Ardèche'),
('FR713', 'Drôme'),
('FR714', 'Isère'),
('FR715', 'Loire'),
('FR716', 'Rhône'),
('FR717', 'Savoie'),
('FR718', 'Haute-Savoie'),
('FR72', 'Auvergne'),
('FR721', 'Allier'),
('FR722', 'Cantal'),
('FR723', 'Haute-Loire'),
('FR724', 'Puy-de-Dôme'),
('FR8', 'Méditerranée'),
('FR81', 'Languedoc-Roussillon'),
('FR811', 'Aude'),
('FR812', 'Gard'),
('FR813', 'Hérault'),
('FR814', 'Lozère'),
('FR815', 'Pyrénées-Orientales'),
('FR82', 'Provence-Alpes-Côte d''Azur'),
('FR821', 'Alpes-de-Haute-Provence'),
('FR822', 'Hautes-Alpes'),
('FR823', 'Alpes-Maritimes'),
('FR824', 'Bouches-du-Rhône'),
('FR825', 'Var'),
('FR826', 'Vaucluse'),
('FR83', 'Corse'),
('FR831', 'Corse-du-Sud'),
('FR832', 'Haute-Corse'),
('FR9', 'Départements d''outre-mer'),
('FR91', 'Guadeloupe'),
('FR910', 'Guadeloupe'),
('FR92', 'Martinique'),
('FR920', 'Martinique'),
('FR93', 'Guyane'),
('FR930', 'Guyane'),
('FR94', 'Réunion'),
('FR940', 'Réunion'),
('FRZ', 'Extra-Regio'),
('FRZZ', 'Extra-Regio'),
('FRZZZ', 'Extra-Regio'),
('GR', 'Griechenland'),
('GR1', 'Βόρεια Ελλάδα'),
('GR11', 'Aνατολική Μακεδονία, Θράκη'),
('GR111', 'Έβρος'),
('GR112', 'Ξάνθη'),
('GR113', 'Ροδόπη'),
('GR114', 'Δράμα'),
('GR115', 'Καβάλα'),
('GR12', 'Κεντρική Μακεδονία'),
('GR121', 'Ημαθία'),
('GR122', 'Θεσσαλονίκη'),
('GR123', 'Κιλκίς'),
('GR124', 'Πέλλα'),
('GR125', 'Πιερία'),
('GR126', 'Σέρρες'),
('GR127', 'Χαλκιδική'),
('GR13', 'Δυτική Μακεδονία'),
('GR131', 'Γρεβενά'),
('GR132', 'Καστοριά'),
('GR133', 'Κοζάνη'),
('GR134', 'Φλώρινα'),
('GR14', 'Θεσσαλία'),
('GR141', 'Καρδίτσα'),
('GR142', 'Λάρισα'),
('GR143', 'Μαγνησία'),
('GR144', 'Τρίκαλα'),
('GR2', 'Κεντρική Ελλάδα'),
('GR21', 'Ήπειρος'),
('GR211', 'Άρτα'),
('GR212', 'Θεσπρωτία'),
('GR213', 'Ιωάννινα'),
('GR214', 'Πρέβεζα'),
('GR22', 'Ιόνια Νησιά'),
('GR221', 'Ζάκυνθος'),
('GR222', 'Κέρκυρα'),
('GR223', 'Κεφαλληνία'),
('GR224', 'Λευκάδα'),
('GR23', 'Δυτική Ελλάδα'),
('GR231', 'Αιτωλοακαρνανία'),
('GR232', 'Αχαΐα'),
('GR233', 'Ηλεία'),
('GR24', 'Στερεά Ελλάδα'),
('GR241', 'Βοιωτία'),
('GR242', 'Εύβοια'),
('GR243', 'Ευρυτανία'),
('GR244', 'Φθιώτιδα'),
('GR245', 'Φωκίδα'),
('GR25', 'Πελοπόννησος'),
('GR251', 'Αργολίδα'),
('GR252', 'Αρκαδία'),
('GR253', 'Κορινθία'),
('GR254', 'Λακωνία'),
('GR255', 'Μεσσηνία'),
('GR3', 'Aττική'),
('GR30', 'Aττική'),
('GR300', 'Aττική'),
('GR4', 'Νησιά Αιγαίου, Κρήτη'),
('GR41', 'Βόρειο Αιγαίο'),
('GR411', 'Λέσβος'),
('GR412', 'Σάμος'),
('GR413', 'Χίος'),
('GR42', 'Νότιο Αιγαίο'),
('GR421', 'Δωδεκάνησος'),
('GR422', 'Κυκλάδες'),
('GR43', 'Κρήτη'),
('GR431', 'Ηράκλειο'),
('GR432', 'Λασίθι'),
('GR433', 'Ρεθύμνη'),
('GR434', 'Χανιά'),
('GRZ', 'Extra-Regio'),
('GRZZ', 'Extra-Regio'),
('GRZZZ', 'Extra-Regio'),
('HR', 'Kroatien'),
('HR0','Hrvatska'),
('HRZ','Extra-Regio'),
('HR03','Jadranska Hrvatska'),
('HR04','Kontinentalna Hrvatska'),
('HRZZ','Extra-Regio NUTS 2'),
('HR031','Primorsko-goranska županija'),
('HR032','Ličko-senjska županija'),
('HR033','Zadarska županija'),
('HR034','Šibensko-kninska županija'),
('HR035','Splitsko-dalmatinska županija'),
('HR036','Istarska županija'),
('HR037','Dubrovačko-neretvanska županija'),
('HR041','Grad Zagreb'),
('HR042','Zagrebačka županija'),
('HR043','Krapinsko-zagorska županija'),
('HR044','Varaždinska županija'),
('HR045','Koprivničko-križevačka županija'),
('HR046','Međimurska županija'),
('HR047','Bjelovarsko-bilogorska županija'),
('HR048','Virovitičko-podravska županija'),
('HR049','Požeško-slavonska županija'),
('HR04A','Brodsko-posavska županija'),
('HR04B','Osječko-baranjska županija'),
('HR04C','Vukovarsko-srijemska županija'),
('HR04D','Karlovačka županija'),
('HR04E','Sisačko-moslavačka županija'),
('HRZZZ','Extra-Regio'),
('HU', 'Ungarn'),
('HU1', 'Közép-Magyarország'),
('HU10', 'Közép-Magyarország'),
('HU101', 'Budapest'),
('HU102', 'Pest'),
('HU2', 'Dunántúl'),
('HU21', 'Közép-Dunántúl'),
('HU211', 'Fejér'),
('HU212', 'Komárom-Esztergom'),
('HU213', 'Veszprém'),
('HU22', 'Nyugat-Dunántúl'),
('HU221', 'Győr-Moson-Sopron'),
('HU222', 'Vas'),
('HU223', 'Zala'),
('HU23', 'Dél-Dunántúl'),
('HU231', 'Baranya'),
('HU232', 'Somogy'),
('HU233', 'Tolna'),
('HU3', 'Alföld és Észak'),
('HU31', 'Észak-Magyarország'),
('HU311', 'Borsod-Abaúj-Zemplén'),
('HU312', 'Heves'),
('HU313', 'Nógrád'),
('HU32', 'Észak-Alföld'),
('HU321', 'Hajdú-Bihar'),
('HU322', 'Jász-Nagykun-Szolnok'),
('HU323', 'Szabolcs-Szatmár-Bereg'),
('HU33', 'Dél-Alföld'),
('HU331', 'Bács-Kiskun'),
('HU332', 'Békés'),
('HU333', 'Csongrád'),
('HUZ', 'Extra-Regio'),
('HUZZ', 'Extra-Regio'),
('HUZZZ', 'Extra-Regio'),
('IE', 'Irland'),
('IE0', 'Ireland'),
('IE01', 'Border, Midland and Western'),
('IE011', 'Border'),
('IE012', 'Midland'),
('IE013', 'West'),
('IE02', 'Southern and Eastern'),
('IE021', 'Dublin'),
('IE022', 'Mid-East'),
('IE023', 'Mid-West'),
('IE024', 'South-East (IRL)'),
('IE025', 'South-West (IRL)'),
('IEZ', 'Extra-Rregio'),
('IEZZ', 'Extra-Regio'),
('IEZZZ', 'Extra-Regio'),
('IS', 'Island'),
('IT', 'Italien'),
('ITC', 'Nord-Ovest'),
('ITC1', 'Piemonte'),
('ITC11', 'Torino'),
('ITC12', 'Vercelli'),
('ITC13', 'Biella'),
('ITC14', 'Verbano-Cusio-Ossola'),
('ITC15', 'Novara'),
('ITC16', 'Cuneo'),
('ITC17', 'Asti'),
('ITC18', 'Alessandria'),
('ITC2', 'Valle d''Aosta/Vallée d''Aoste'),
('ITC20', 'Valle d''Aosta/Vallée d''Aoste'),
('ITC3', 'Liguria'),
('ITC31', 'Imperia'),
('ITC32', 'Savona'),
('ITC33', 'Genova'),
('ITC34', 'La Spezia'),
('ITC4', 'Lombardia'),
('ITC41', 'Varese'),
('ITC42', 'Como'),
('ITC43', 'Lecco'),
('ITC44', 'Sondrio'),
('ITC45', 'Milano'),
('ITC46', 'Bergamo'),
('ITC47', 'Brescia'),
('ITC48', 'Pavia'),
('ITC49', 'Lodi'),
('ITC4A', 'Cremona'),
('ITC4B', 'Mantova'),
('ITD', 'Nord-Est'),
('ITD1', 'Provincia Autonoma Bolzano/Bozen [3]'),
('ITD10', 'Bolzano-Bozen'),
('ITD2', 'Provincia Autonoma Trento'),
('ITD20', 'Trento'),
('ITD3', 'Veneto'),
('ITD31', 'Verona'),
('ITD32', 'Vicenza'),
('ITD33', 'Belluno'),
('ITD34', 'Treviso'),
('ITD35', 'Venezia'),
('ITD36', 'Padova'),
('ITD37', 'Rovigo'),
('ITD4', 'Friuli-Venezia Giulia'),
('ITD41', 'Pordenone'),
('ITD42', 'Udine'),
('ITD43', 'Gorizia'),
('ITD44', 'Trieste'),
('ITD5', 'Emilia-Romagna'),
('ITD51', 'Piacenza'),
('ITD52', 'Parma'),
('ITD53', 'Reggio nell''Emilia'),
('ITD54', 'Modena'),
('ITD55', 'Bologna'),
('ITD56', 'Ferrara'),
('ITD57', 'Ravenna'),
('ITD58', 'Forlì-Cesena'),
('ITD59', 'Rimini'),
('ITE', 'Centro (i)'),
('ITE1', 'Toscana'),
('ITE11', 'Massa-Carrara'),
('ITE12', 'Lucca'),
('ITE13', 'Pistoia'),
('ITE14', 'Firenze'),
('ITE15', 'Prato'),
('ITE16', 'Livorno'),
('ITE17', 'Pisa'),
('ITE18', 'Arezzo'),
('ITE19', 'Siena'),
('ITE1A', 'Grosseto'),
('ITE2', 'Umbria'),
('ITE21', 'Perugia'),
('ITE22', 'Terni'),
('ITE3', 'Marche'),
('ITE31', 'Pesaro e Urbino'),
('ITE32', 'Ancona'),
('ITE33', 'Macerata'),
('ITE34', 'Ascoli Piceno'),
('ITE4', 'Lazio'),
('ITE41', 'Viterbo'),
('ITE42', 'Rieti'),
('ITE43', 'Roma'),
('ITE44', 'Latina'),
('ITE45', 'Frosinone'),
('ITF', 'Sud'),
('ITF1', 'Abruzzo'),
('ITF11', 'L''Aquila'),
('ITF12', 'Teramo'),
('ITF13', 'Pescara'),
('ITF14', 'Chieti'),
('ITF2', 'Molise'),
('ITF21', 'Isernia'),
('ITF22', 'Campobasso'),
('ITF3', 'Campania'),
('ITF31', 'Caserta'),
('ITF32', 'Benevento'),
('ITF33', 'Napoli'),
('ITF34', 'Avellino'),
('ITF35', 'Salerno'),
('ITF4', 'Puglia'),
('ITF41', 'Foggia'),
('ITF42', 'Bari'),
('ITF43', 'Taranto'),
('ITF44', 'Brindisi'),
('ITF45', 'Lecce'),
('ITF5', 'Basilicata'),
('ITF51', 'Potenza'),
('ITF52', 'Matera'),
('ITF6', 'Calabria'),
('ITF61', 'Cosenza'),
('ITF62', 'Crotone'),
('ITF63', 'Catanzaro'),
('ITF64', 'Vibo Valentia'),
('ITF65', 'Reggio di Calabria'),
('ITG', 'Isole'),
('ITG1', 'Sicilia'),
('ITG11', 'Trapani'),
('ITG12', 'Palermo'),
('ITG13', 'Messina'),
('ITG14', 'Agrigento'),
('ITG15', 'Caltanissetta'),
('ITG16', 'Enna'),
('ITG17', 'Catania'),
('ITG18', 'Ragusa'),
('ITG19', 'Siracusa'),
('ITG2', 'Sardegna'),
('ITG25', 'Sassari'),
('ITG26', 'Nuoro'),
('ITG27', 'Cagliari'),
('ITG28', 'Oristano'),
('ITG29', 'Olbia-Tempio'),
('ITG2A', 'Ogliastra'),
('ITG2B', 'Medio Campidano'),
('ITG2C', 'Carbonia-Iglesias'),
('ITZ', 'Extra-Regio'),
('ITZZ', 'Extra-Regio'),
('ITZZZ', 'Extra-Regio'),
('LI', 'Liechtenstein'),
('LT', 'Litauen'),
('LT0', 'lietuva'),
('LT00', 'Lietuva'),
('LT001', 'Alytaus apskritis'),
('LT002', 'Kauno apskritis'),
('LT003', 'Klaipėdos apskritis'),
('LT004', 'Marijampolės apskritis'),
('LT005', 'Panevėžio apskritis'),
('LT006', 'Šiaulių apskritis'),
('LT007', 'Tauragės apskritis'),
('LT008', 'Telšių apskritis'),
('LT009', 'Utenos apskritis'),
('LT00A', 'Vilniaus apskritis'),
('LTZ', 'Extra-Regio'),
('LTZZ', 'Extra-Regio'),
('LTZZZ', 'Extra-Regio'),
('LU', 'Luxemburg'),
('LU0', 'Luxembourg (Grand-Duché)'),
('LU00', 'Luxembourg (Grand-Duché)'),
('LU000', 'Luxembourg (Grand-Duché)'),
('LUZ', 'Extra-Regio'),
('LUZZ', 'Extra-Regio'),
('LUZZZ', 'Extra-Regio'),
('LV', 'Lettland'),
('LV0', 'latvija'),
('LV00', 'Latvija'),
('LV003', 'Kurzeme'),
('LV005', 'Latgale'),
('LV006', 'Rīga'),
('LV007', 'Pierīga'),
('LV008', 'Vidzeme'),
('LV009', 'Zemgale'),
('LVZ', 'Extra-Regio'),
('LVZZ', 'Extra-Regio'),
('LVZZZ', 'Extra-Regio'),
('MT', 'Malta'),
('MT0', 'Malta'),
('MT00', 'Malta'),
('MT001', 'Malta'),
('MT002', 'Gozo and Comino/Għawdex u Kemmuna'),
('MTZ', 'Extra-Regio'),
('MTZZ', 'Extra-Regio'),
('MTZZZ', 'Extra-Regio'),
('NL', 'Niederlande'),
('NL1', 'Noord-Nederland'),
('NL11', 'Groningen'),
('NL111', 'Oost-Groningen'),
('NL112', 'Delfzijl en omgeving'),
('NL113', 'Overig Groningen'),
('NL12', 'Friesland (NL)'),
('NL121', 'Noord-Friesland'),
('NL122', 'Zuidwest-Friesland'),
('NL123', 'Zuidoost-Friesland'),
('NL13', 'Drenthe'),
('NL131', 'Noord-Drenthe'),
('NL132', 'Zuidoost-Drenthe'),
('NL133', 'Zuidwest-Drenthe'),
('NL2', 'Oost-Nederland'),
('NL21', 'Overijssel'),
('NL211', 'Noord-Overijssel'),
('NL212', 'Zuidwest-Overijssel'),
('NL213', 'Twente'),
('NL22', 'Gelderland'),
('NL221', 'Veluwe'),
('NL224', 'Zuidwest-Gelderland'),
('NL225', 'Achterhoek'),
('NL226', 'Arnhem/Nijmegen'),
('NL23', 'Flevoland'),
('NL230', 'Flevoland'),
('NL3', 'West-Nederland'),
('NL31', 'Utrecht'),
('NL310', 'Utrecht'),
('NL32', 'Noord-Holland'),
('NL321', 'Kop van Noord-Holland'),
('NL322', 'Alkmaar en omgeving'),
('NL323', 'IJmond'),
('NL324', 'Agglomeratie Haarlem'),
('NL325', 'Zaanstreek'),
('NL326', 'Groot-Amsterdam'),
('NL327', 'Het Gooi en Vechtstreek'),
('NL33', 'Zuid-Holland'),
('NL331', 'Agglomeratie Leiden en Bollenstreek'),
('NL332', 'Agglomeratie ''s-Gravenhage'),
('NL333', 'Delft en Westland'),
('NL334', 'Oost-Zuid-Holland'),
('NL335', 'Groot-Rijnmond'),
('NL336', 'Zuidoost-Zuid-Holland'),
('NL34', 'Zeeland'),
('NL341', 'Zeeuwsch-Vlaanderen'),
('NL342', 'Overig Zeeland'),
('NL4', 'Zuid-Nederland'),
('NL41', 'Noord-Brabant'),
('NL411', 'West-Noord-Brabant'),
('NL412', 'Midden-Noord-Brabant'),
('NL413', 'Noordoost-Noord-Brabant'),
('NL414', 'Zuidoost-Noord-Brabant'),
('NL42', 'Limburg (NL)'),
('NL421', 'Noord-Limburg'),
('NL422', 'Midden-Limburg'),
('NL423', 'Zuid-Limburg'),
('NLZ', 'Extra-Regio'),
('NLZZ', 'Extra-Regio'),
('NLZZZ', 'Extra-Regio'),
('NO', 'Norwegen'),
('NO0', 'Kongeriket Norge'),
('NO01', 'Oslo og Akershus'),
('NO011', 'Oslo'),
('NO012', 'Akershus'),
('NO02', 'Hedmark og Oppland'),
('NO021', 'Hedmark'),
('NO022', 'Oppland'),
('NO03', 'Sør-Østlandet'),
('NO031', 'Østfold'),
('NO032', 'Buskerud'),
('NO033', 'Vestfold'),
('NO034', 'Telemark'),
('NO04', 'Agder og Rogaland'),
('NO041', 'Aust-Agder'),
('NO042', 'Vest-Agder'),
('NO043', 'Rogaland'),
('NO05', 'Vestlandet'),
('NO051', 'Hordaland'),
('NO052', 'Sogn og Fjordane'),
('NO053', 'Møre og Romsdal'),
('NO06', 'Trøndelag'),
('NO061', 'Sør-Trøndelag'),
('NO062', 'Nord-Trøndelag'),
('NO07', 'Nord-Norge'),
('NO071', 'Nordland'),
('NO072', 'Troms'),
('NO073', 'Finnmark'),
('PL', 'Polen'),
('PL1', 'Region Centralny'),
('PL11', 'Łódzkie'),
('PL113', 'Miasto Łódź'),
('PL114', 'Łódzki'),
('PL115', 'Piotrkowski'),
('PL116', 'Sieradzki'),
('PL117', 'Skierniewicki'),
('PL12', 'Mazowieckie'),
('PL121', 'Ciechanowsko-płocki'),
('PL122', 'Ostrołęcko-siedlecki'),
('PL127', 'Miasto Warszawa'),
('PL128', 'Radomski'),
('PL129', 'Warszawski-wschodni'),
('PL12A', 'Warszawski-zachodni'),
('PL2', 'Region Południowy'),
('PL21', 'Małopolskie'),
('PL213', 'Miasto Kraków'),
('PL214', 'Krakowski'),
('PL215', 'Nowosądecki'),
('PL216', 'Oświęcimski'),
('PL217', 'Tarnowski'),
('PL22', 'Śląskie'),
('PL224', 'Częstochowski'),
('PL225', 'Bielski'),
('PL227', 'Rybnicki'),
('PL228', 'Bytomski'),
('PL229', 'Gliwicki'),
('PL22A', 'Katowicki'),
('PL22B', 'Sosnowiecki'),
('PL22C', 'Tyski'),
('PL3', 'Region Wschodni'),
('PL31', 'Lubelskie'),
('PL311', 'Bialski'),
('PL312', 'Chełmsko-zamojski'),
('PL314', 'Lubelski'),
('PL315', 'Puławski'),
('PL32', 'Podkarpackie'),
('PL323', 'Krośnieński'),
('PL324', 'Przemyski'),
('PL325', 'Rzeszowski'),
('PL326', 'Tarnobrzeski'),
('PL33', 'Świętokrzyskie'),
('PL331', 'Kielecki'),
('PL332', 'Sandomiersko-jędrzejowski'),
('PL34', 'Podlaskie'),
('PL343', 'Białostocki'),
('PL344', 'Łomżyński'),
('PL345', 'Suwalski'),
('PL4', 'Region Północno-zachodni'),
('PL41', 'Wielkopolskie'),
('PL411', 'Pilski'),
('PL414', 'Koniński'),
('PL415', 'Miasto Poznań'),
('PL416', 'Kaliski'),
('PL417', 'Leszczyński'),
('PL418', 'Poznański'),
('PL42', 'Zachodniopomorskie'),
('PL422', 'Koszaliński'),
('PL423', 'Stargardzki'),
('PL424', 'Miasto Szczecin'),
('PL425', 'Szczeciński'),
('PL43', 'Lubuskie'),
('PL431', 'Gorzowski'),
('PL432', 'Zielonogórski'),
('PL5', 'Region Południowo-zachodni'),
('PL51', 'Dolnośląskie'),
('PL514', 'Miasto Wrocław'),
('PL515', 'Jeleniogórski'),
('PL516', 'Legnicko-głogowski'),
('PL517', 'Wałbrzyski'),
('PL518', 'Wrocławski'),
('PL52', 'Opolskie'),
('PL521', 'Nyski'),
('PL522', 'Opolski'),
('PL6', 'Region Północny'),
('PL61', 'Kujawsko-pomorskie'),
('PL613', 'Bydgosko-toruński'),
('PL614', 'Grudziądzki'),
('PL615', 'Włocławski'),
('PL62', 'Warmińsko-mazurskie'),
('PL621', 'Elbląski'),
('PL622', 'Olsztyński'),
('PL623', 'Ełcki'),
('PL63', 'Pomorskie'),
('PL631', 'Słupski'),
('PL633', 'Trójmiejski'),
('PL634', 'Gdański'),
('PL635', 'Starogardzki'),
('PLZ', 'Extra-Regio'),
('PLZZ', 'Extra-Regio'),
('PLZZZ', 'Extra-Regio'),
('PT', 'Portugal'),
('PT1', 'Continente'),
('PT11', 'Norte'),
('PT111', 'Minho-Lima'),
('PT112', 'Cávado'),
('PT113', 'Ave'),
('PT114', 'Grande Porto'),
('PT115', 'Tâmega'),
('PT116', 'Entre Douro e Vouga'),
('PT117', 'Douro'),
('PT118', 'Alto Trás-os-Montes'),
('PT15', 'Algarve'),
('PT150', 'Algarve'),
('PT16', 'Centro (P)'),
('PT161', 'Baixo Vouga'),
('PT162', 'Baixo Mondego'),
('PT163', 'Pinhal Litoral'),
('PT164', 'Pinhal Interior Norte'),
('PT165', 'Dâo-Lafôes'),
('PT166', 'Pinhal Interior Sul'),
('PT167', 'Serra da Estrela'),
('PT168', 'Beira Interior Norte'),
('PT169', 'Beira Interior Sul'),
('PT16A', 'Cova da Beira'),
('PT16B', 'Oeste'),
('PT16C', 'Médio Tejo'),
('PT17', 'Lisboa'),
('PT171', 'Grande Lisboa'),
('PT172', 'Península de Setúbal'),
('PT18', 'Alentejo'),
('PT181', 'Alentejo Litoral'),
('PT182', 'Alto Alentejo'),
('PT183', 'Alentejo Central'),
('PT184', 'Baixo Alentejo'),
('PT185', 'Lezíria do Tejo'),
('PT2', 'Região AAutónoma dos Açores'),
('PT20', 'Região Autónoma dos Açores'),
('PT200', 'Região Autónoma dos Açores'),
('PT3', 'Região Autónoma da Madeira'),
('PT30', 'Região Autónoma da Madeira'),
('PT300', 'Região Autónoma da Madeira'),
('PTZ', 'Extra-Regio'),
('PTZZ', 'Extra-Regio'),
('PTZZZ', 'Extra-Regio'),
('RO', 'Rumänien'),
('RO1','Macroregiunea Unu'),
('RO2','Macroregiunea Doi'),
('RO3','Macroregiunea Trei'),
('RO4','Macroregiunea Patru'),
('ROZ','Extra-Regio'),
('RO11','Nord-Vest'),
('RO12','Centru'),
('RO21','Nord-Est'),
('RO22','Sud-Est'),
('RO31','Sud - Muntenia'),
('RO32','Bucureşti - Ilfov'),
('RO41','Sud-Vest Oltenia'),
('RO42','Vest'),
('ROZZ','Extra-Regio NUTS 2'),
('RO111','Bihor'),
('RO112','Bistriţa-Năsăud'),
('RO113','Cluj'),
('RO114','Maramureş'),
('RO115','Satu Mare'),
('RO116','Sălaj'),
('RO121','Alba'),
('RO122','Braşov'),
('RO123','Covasna'),
('RO124','Harghita'),
('RO125','Mureş'),
('RO126','Sibiu'),
('RO211','Bacău'),
('RO212','Botoşani'),
('RO213','Iaşi'),
('RO214','Neamţ'),
('RO215','Suceava'),
('RO216','Vaslui'),
('RO221','Brăila'),
('RO222','Buzău'),
('RO223','Constanţa'),
('RO224','Galaţi'),
('RO225','Tulcea'),
('RO226','Vrancea'),
('RO311','Argeş'),
('RO312','Călăraşi'),
('RO313','Dâmboviţa'),
('RO314','Giurgiu'),
('RO315','Ialomiţa'),
('RO316','Prahova'),
('RO317','Teleorman'),
('RO321','Bucureşti'),
('RO322','Ilfov'),
('RO411','Dolj'),
('RO412','Gorj'),
('RO413','Mehedinţi'),
('RO414','Olt'),
('RO415','Vâlcea'),
('RO421','Arad'),
('RO422','Caraş-Severin'),
('RO423','Hunedoara'),
('RO424','Timiş'),
('ROZZZ','Extra-Regio'),
('SE', 'Schweden'),
('SE1', 'Östra Sverige'),
('SE11', 'Stockholm'),
('SE110', 'Stockholms län'),
('SE12', 'Östra Mellansverige'),
('SE121', 'Uppsala län'),
('SE122', 'Södermanlands län'),
('SE123', 'Östergötlands län'),
('SE124', 'Örebro län'),
('SE125', 'Västmanlands län'),
('SE2', 'Södra Sverige'),
('SE21', 'Småland med öarna'),
('SE211', 'Jönköpings län'),
('SE212', 'Kronobergs län'),
('SE213', 'Kalmar län'),
('SE214', 'Gotlands län'),
('SE22', 'Sydsverige'),
('SE221', 'Blekinge län'),
('SE224', 'Skåne län'),
('SE23', 'Västsverige'),
('SE231', 'Hallands län'),
('SE232', 'Västra Götalands län'),
('SE3', 'Norra Sverige'),
('SE31', 'Norra Mellansverige'),
('SE311', 'Värmlands län'),
('SE312', 'Dalarnas län'),
('SE313', 'Gävleborgs län'),
('SE32', 'Mellersta Norrland'),
('SE321', 'Västernorrlands län'),
('SE322', 'Jämtlands län'),
('SE33', 'Övre Norrland'),
('SE331', 'Västerbottens län'),
('SE332', 'Norrbottens län'),
('SEZ', 'Extra-Regio'),
('SEZZ', 'Extra-Regio'),
('SEZZZ', 'Extra-Regio'),
('SI', 'Slowenien'),
('SI0', 'Slovenija'),
('SI01', 'Vzhodna Slovenija'),
('SI011', 'Pomurska'),
('SI012', 'Podravska'),
('SI013', 'Koroška'),
('SI014', 'Savinjska'),
('SI015', 'Zasavska'),
('SI016', 'Spodnjeposavska'),
('SI017', 'Jugovzhodna Slovenija'),
('SI018', 'Notranjsko-kraška'),
('SI02', 'Zahodna Slovenija'),
('SI021', 'Osrednjeslovenska'),
('SI022', 'Gorenjska'),
('SI023', 'Goriška'),
('SI024', 'Obalno-kraška'),
('SIZ', 'Extra-Regio'),
('SIZZ', 'Extra-Regio'),
('SIZZZ', 'Extra-Regio'),
('SK', 'Slowakai'),
('SK0', 'Slovenská republika'),
('SK01', 'Bratislavský kraj'),
('SK010', 'Bratislavský kraj'),
('SK02', 'Západné Slovensko'),
('SK021', 'Trnavský kraj'),
('SK022', 'Trenčiansky kraj'),
('SK023', 'Nitriansky kraj'),
('SK03', 'Stredné Slovensko'),
('SK031', 'Žilinský kraj'),
('SK032', 'Banskobystrický kraj'),
('SK04', 'Východné Slovensko'),
('SK041', 'Prešovský kraj'),
('SK042', 'Košický kraj'),
('SKZ', 'Extra-Regio'),
('SKZZ', 'Extra-Regio'),
('SKZZZ', 'Extra-Regio'),
('TR', 'Türkei'),
('TR1', 'İstanbul'),
('TR2', 'Batı Marmara'),
('TE3', 'Ege'),
('TR4', 'Doğu Marmara'),
('TR5', 'Batı Anadolu'),
('TR6', 'Akdeniz'),
('TR7', 'Orta Anadolu'),
('TR8', 'Batı Karadeniz'),
('TR9', 'Doğu Karadeniz'),
('TRA', 'Kuzeydoğu Anadolu'),
('TRB', 'Ortadoğu Anadolu'),
('TRC', 'Güneydoğu Anadolu'),
('TRZ', 'Extra-Regio'),
('TR10', 'İstanbul'),
('TR21', 'Tekirdağ'),
('TR22', 'Balıkesir'),
('TR31', 'İzmir'),
('TR32', 'Aydın'),
('TR33', 'Manisa'),
('TR41', 'Bursa'),
('TR42', 'Kocaeli'),
('TR51', 'Ankara'),
('TR52', 'Konya'),
('TR61', 'Antalya'),
('TR62', 'Adana'),
('TR63', 'Hatay'),
('TR71', 'Kırıkkale'),
('TR72', 'Kayseri'),
('TR81', 'Zonguldak'),
('TR82', 'Kastamonu'),
('TR83', 'Samsun'),
('TR90', 'Trabzon'),
('TRA1', 'Erzurum'),
('TRA2', 'Ağrı'),
('TRB1', 'Malatya'),
('TRB2', 'Van'),
('TRC1', 'Gaziantep'),
('TRC2', 'Şanlıurfa'),
('TRC3', 'Mardin'),
('TR100', 'İstanbul'),
('TR211', 'Tekirdağ'),
('TR212', 'Edirne'),
('TR213', 'Kırklareli'),
('TR221', 'Balıkesir'),
('TR222', 'Canakkale'),
('TR310', 'İzmir'),
('TR321', 'Aydın'),
('TR322', 'Denizli'),
('TR323', 'Muğla'),
('TR331', 'Manisa'),
('TR332', 'Afyon '),
('TR333', 'Kütahya'),
('TR334', 'Uşak'),
('TR411', 'Bursa'),
('TR412', 'Eskişehir'),
('TR413', 'Bilecik'),
('TR421', 'Kocaeli'),
('TR422', 'Sakarya'),
('TR423', 'Düzce'),
('TR424', 'Bolu'),
('TR425', 'Yalova'),
('TR510', 'Ankara'),
('TR521', 'Konya'),
('TR522', 'Karaman'),
('TR611', 'Antalya'),
('TR612', 'Isparta'),
('TR613', 'Burdur'),
('TR621', 'Adana'),
('TR622', 'İcel'),
('TR631', 'Hatay'),
('TR632', 'Kahramanmaraş'),
('TR633', 'Osmaniye'),
('TR711', 'Kırıkkale'),
('TR712', 'Aksaray'),
('TR713', 'Niğde'),
('TR714', 'Nevşehir'),
('TR715', 'Kırşehir'),
('TR721', 'Kayseri'),
('TR722', 'Sivas'),
('TR723', 'Yozgat'),
('TR811', 'Zonguldak'),
('TR812', 'Karabük'),
('TR813', 'Bartın'),
('TR821', 'Kastamonu'),
('TR822', 'Çankırı'),
('TR823', 'Sinop'),
('TR831', 'Samsun'),
('TR832', 'Tokat'),
('TR833', 'Çorum'),
('TR834', 'Amasya'),
('TR901', 'Trabzon'),
('TR902', 'Ordu'),
('TR903', 'Giresun'),
('TR904', 'Rize'),
('TR905', 'Artvin'),
('TR906', 'Gümüşhane'),
('TRA11', 'Erzurum'),
('TRA12', 'Erzincan'),
('TRA13', 'Bayburt'),
('TRA21', 'Ağrı'),
('TRA22', 'Kars'),
('TRA23', 'Iğdır'),
('TRA24', 'Ardahan'),
('TRB11', 'Malatya'),
('TRB12', 'Elazığ'),
('TRB13', 'Bingöl'),
('TRB14', 'Tunceli'),
('TRB21', 'Van'),
('TRB22', 'Muş'),
('TRB23', 'Bitlis'),
('TRB24', 'Hakkari'),
('TRC11', 'Gaziantep'),
('TRC12', 'Adıyaman'),
('TRC13', 'Kilis'),
('TRC21', 'Şanlıurfa'),
('TRC22', 'Diyarbakır'),
('TRC31', 'Mardin'),
('TRC32', 'Batman'),
('TRC33', 'Şırnak'),
('TRC34', 'Siirt'),
('UK', 'Großbritannien'),
('UKC', 'North East (England)'),
('UKC1', 'Tees Valley and Durham'),
('UKC11', 'Hartlepool and Stockton-on-Tees'),
('UKC12', 'South Teesside'),
('UKC13', 'Darlington'),
('UKC14', 'Durham CC'),
('UKC2', 'Northumberland and Tyne and Wear'),
('UKC21', 'Northumberland'),
('UKC22', 'Tyneside'),
('UKC23', 'Sunderland'),
('UKD', 'North West (England)'),
('UKD1', 'Cumbria'),
('UKD11', 'West Cumbria'),
('UKD12', 'East Cumbria'),
('UKD2', 'Cheshire'),
('UKD21', 'Halton and Warrington'),
('UKD22', 'Cheshire CC'),
('UKD3', 'Greater Manchester'),
('UKD31', 'Greater Manchester South'),
('UKD32', 'Greater Manchester North'),
('UKD4', 'Lancashire'),
('UKD41', 'Blackburn with Darwen'),
('UKD42', 'Blackpool'),
('UKD43', 'Lancashire CC'),
('UKD5', 'Merseyside'),
('UKD51', 'East Merseyside'),
('UKD52', 'Liverpool'),
('UKD53', 'Sefton'),
('UKD54', 'Wirral'),
('UKE', 'Yorkshire and the Humber'),
('UKE1', 'East Yorkshire and Northern Lincolnshire'),
('UKE11', 'Kingston upon Hull, City of'),
('UKE12', 'East Riding of Yorkshire'),
('UKE13', 'North and North East Lincolnshire'),
('UKE2', 'North Yorkshire'),
('UKE21', 'York'),
('UKE22', 'North Yorkshire CC'),
('UKE3', 'South Yorkshire'),
('UKE31', 'Barnsley, Doncaster and Rotherham'),
('UKE32', 'Sheffield'),
('UKE4', 'West Yorkshire'),
('UKE41', 'Bradford'),
('UKE42', 'Leeds'),
('UKE43', 'Calderdale, Kirklees and Wakefield'),
('UKF', 'East Midlands (England)'),
('UKF1', 'Derbyshire and Nottinghamshire'),
('UKF11', 'Derby'),
('UKF12', 'East Derbyshire'),
('UKF13', 'South and West Derbyshire'),
('UKF14', 'Nottingham'),
('UKF15', 'North Nottinghamshire'),
('UKF16', 'South Nottinghamshire'),
('UKF2', 'Leicestershire, Rutland and Northamptonshire'),
('UKF21', 'Leicester'),
('UKF22', 'Leicestershire CC and Rutland'),
('UKF23', 'Northamptonshire'),
('UKF3', 'Lincolnshire'),
('UKF30', 'Lincolnshire'),
('UKG', 'West Midlands (England)'),
('UKG1', 'Herefordshire, Worcestershire and Warwickshire'),
('UKG11', 'Herefordshire, County of'),
('UKG12', 'Worcestershire'),
('UKG13', 'Warwickshire'),
('UKG2', 'Shropshire and Staffordshire'),
('UKG21', 'Telford and Wrekin'),
('UKG22', 'Shropshire CC'),
('UKG23', 'Stoke-on-Trent'),
('UKG24', 'Staffordshire CC'),
('UKG3', 'West Midlands'),
('UKG31', 'Birmingham'),
('UKG32', 'Solihull'),
('UKG33', 'Coventry'),
('UKG34', 'Dudley and Sandwell'),
('UKG35', 'Walsall and Wolverhampton'),
('UKH', 'East of England'),
('UKH1', 'East Anglia'),
('UKH11', 'Peterborough'),
('UKH12', 'Cambridgeshire CC'),
('UKH13', 'Norfolk'),
('UKH14', 'Suffolk'),
('UKH2', 'Bedfordshire and Hertfordshire'),
('UKH21', 'Luton'),
('UKH22', 'Bedfordshire CC'),
('UKH23', 'Hertfordshire'),
('UKH3', 'Essex'),
('UKH31', 'Southend-on-Sea'),
('UKH32', 'Thurrock'),
('UKH33', 'Essex CC'),
('UKI', 'London'),
('UKI1', 'Inner London'),
('UKI11', 'Inner London — West'),
('UKI12', 'Inner London — East'),
('UKI2', 'Outer London'),
('UKI21', 'Outer London — East and North East'),
('UKI22', 'Outer London — South'),
('UKI23', 'Outer London — West and North West'),
('UKJ', 'South East (England)'),
('UKJ1', 'Berkshire, Buckinghamshire and Oxfordshire'),
('UKJ11', 'Berkshire'),
('UKJ12', 'Milton Keynes'),
('UKJ13', 'Buckinghamshire CC'),
('UKJ14', 'Oxfordshire'),
('UKJ2', 'Surrey, East and West Sussex'),
('UKJ21', 'Brighton and Hove'),
('UKJ22', 'East Sussex CC'),
('UKJ23', 'Surrey'),
('UKJ24', 'West Sussex'),
('UKJ3', 'Hampshire and Isle of Wight'),
('UKJ31', 'Portsmouth'),
('UKJ32', 'Southampton'),
('UKJ33', 'Hampshire CC'),
('UKJ34', 'Isle of Wight'),
('UKJ4', 'Kent'),
('UKJ41', 'Medway'),
('UKJ42', 'Kent CC'),
('UKK', 'South West (England)'),
('UKK1', 'Gloucestershire, Wiltshire and Bristol/Bath area'),
('UKK11', 'Bristol, City of'),
('UKK12', 'Bath and North East Somerset, North Somerset and South Gloucestershire'),
('UKK13', 'Gloucestershire'),
('UKK14', 'Swindon'),
('UKK15', 'Wiltshire CC'),
('UKK2', 'Dorset and Somerset'),
('UKK21', 'Bournemouth and Poole'),
('UKK22', 'Dorset CC'),
('UKK23', 'Somerset'),
('UKK3', 'Cornwall and Isles of Scilly'),
('UKK30', 'Cornwall and Isles of Scilly'),
('UKK4', 'Devon'),
('UKK41', 'Plymouth'),
('UKK42', 'Torbay'),
('UKK43', 'Devon CC'),
('UKL', 'Wales'),
('UKL1', 'West Wales and The Valleys'),
('UKL11', 'Isle of Anglesey'),
('UKL12', 'Gwynedd'),
('UKL13', 'Conwy and Denbighshire'),
('UKL14', 'South West Wales'),
('UKL15', 'Central Valleys'),
('UKL16', 'Gwent Valleys'),
('UKL17', 'Bridgend and Neath Port Talbot'),
('UKL18', 'Swansea'),
('UKL2', 'East Wales'),
('UKL21', 'Monmouthshire and Newport'),
('UKL22', 'Cardiff and Vale of Glamorgan'),
('UKL23', 'Flintshire and Wrexham'),
('UKL24', 'Powys'),
('UKM', 'Scotland'),
('UKM2', 'Eastern Scotland'),
('UKM21', 'Angus and Dundee City'),
('UKM22', 'Clackmannanshire and Fife'),
('UKM23', 'East Lothian and Midlothian'),
('UKM24', 'Scottish Borders'),
('UKM25', 'Edinburgh, City of'),
('UKM26', 'Falkirk'),
('UKM27', 'Perth & Kinross and Stirling'),
('UKM28', 'West Lothian'),
('UKM3', 'South Western Scotland'),
('UKM31', 'East Dunbartonshire, West Dunbartonshire and Helensburgh & Lomond'),
('UKM32', 'Dumfries & Galloway'),
('UKM33', 'East Ayrshire and North Ayrshire mainland'),
('UKM34', 'Glasgow City'),
('UKM35', 'Inverclyde, East Renfrewshire and Renfrewshire'),
('UKM36', 'North Lanarkshire'),
('UKM37', 'South Ayrshire'),
('UKM38', 'South Lanarkshire'),
('UKM5', 'North Eastern Scotland'),
('UKM50', 'Aberdeen City and Aberdeenshire'),
('UKM6', 'Highlands and Islands'),
('UKM61', 'Caithness & Sutherland and Ross & Cromarty'),
('UKM62', 'Inverness & Nairn and Moray, Badenoch & Strathspey'),
('UKM63', 'Lochaber, Skye & Lochalsh, Arran & Cumbrae and Argyll & Bute'),
('UKM64', 'Eilean Siar (Western Isles)'),
('UKM65', 'Orkney Islands'),
('UKM66', 'Shetland Islands'),
('UKN', 'Northern Ireland'),
('UKN0', 'Northern Ireland'),
('UKN01', 'Belfast'),
('UKN02', 'Outer Belfast'),
('UKN03', 'East of Northern Ireland'),
('UKN04', 'North of Northern Ireland'),
('UKN05', 'West and South of Northern Ireland'),
('UKZ', 'Extra-Regio'),
('UKZZ', 'Extra-Regio'),
('UKZZZ', 'Extra-Regio');
