tinyMCE.addI18n('is.media_dlg',{
title:"Setja inn / Breyta birtingu margmi\u00F0lunar",
general:"Almennt",
advanced:"\u00CDtarlegt",
file:"Skr\u00E1/Sl\u00F3\u00F0",
list:"Listi",
size:"V\u00EDddir",
preview:"Forsko\u00F0un",
constrain_proportions:"Halda hlutf\u00F6llum",
type:"Ger\u00F0",
id:"Id",
name:"Nafn",
class_name:"Flokkur",
vspace:"L\u00F3\u00F0r-bil",
hspace:"L\u00E1r-bil",
play:"Sj\u00E1lfvirk spilun",
loop:"Endurtaka",
menu:"S\u00FDna valmynd",
quality:"G\u00E6\u00F0i",
scale:"A\u00F0l\u00F6gun",
align:"J\u00F6fnun",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Bakgrunnur",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Hidden",
controller:"Controller",
kioskmode:"Kiosk mode",
playeveryframe:"Play every frame",
targetcache:"Target cache",
correction:"No correction",
enablejavascript:"Enable JavaScript",
starttime:"Start time",
endtime:"End time",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Target",
volume:"Volume",
autostart:"Byrja sj\u00E1lfvirkt",
enabled:"Virkt",
fullscreen:"Heilskj\u00E1r",
invokeurls:"Virkja sl\u00F3\u00F0ir",
mute:"Dempa",
stretchtofit:"Teigja til a\u00F0 passa",
windowlessvideo:"Gluggalaust myndband",
balance:"Balance",
baseurl:"Base URL",
captioningid:"Captioning id",
currentmarker:"Current marker",
currentposition:"Current position",
defaultframe:"Upprunalegur rammi",
playcount:"Play count",
rate:"Rate",
uimode:"UI Mode",
flash_options:"Flash m\u00F6guleikar",
qt_options:"Quicktime m\u00F6guleikar",
wmp_options:"Windows media player m\u00F6guleikar",
rmp_options:"Real media player m\u00F6guleikar",
shockwave_options:"Shockwave m\u00F6guleikar",
autogotourl:"Auto goto URL",
center:"Mi\u00F0ja",
imagestatus:"Sta\u00F0a myndar",
maintainaspect:"Halda hlutf\u00F6llum",
nojava:"Ekkert java",
prefetch:"Prefetch",
shuffle:"Shuffle",
console:"Console",
numloop:"Num loops",
controls:"Stj\u00F3rn",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Hlj\u00F3\u00F0",
progress:"Sta\u00F0a",
qtsrc:"QT Src",
qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
align_top:"Efst",
align_right:"H\u00E6gri",
align_bottom:"Ne\u00F0st",
align_left:"Vinstri",
align_center:"Mi\u00F0ja",
align_top_left:"Efst vinstri",
align_top_right:"Efst h\u00E6gri",
align_bottom_left:"Ne\u00F0st vinstri",
align_bottom_right:"Ne\u00F0st h\u00E6gri",
flv_options:"Flash m\u00F6guleikar",
flv_scalemode:"Scale mode",
flv_buffer:"Buffer",
flv_startimage:"Start image",
flv_starttime:"Start time",
flv_defaultvolume:"Default volumne",
flv_hiddengui:"Hidden GUI",
flv_autostart:"Auto start",
flv_loop:"Loop",
flv_showscalemodes:"Show scale modes",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});