// --------------------------------------------------------------
// gpx.js
// 
// © 2025 hxdimpf Resarch
//
// This file is part of GCxM.
// Licensed under the MIT License.
//
// You may use, copy, modify, and distribute this software
// under the terms of the MIT License.
//
// https://opensource.org/licenses/MIT
// --------------------------------------------------------------

import { apiFetch } from './api.js';
import { escapeXml } from './helpers.js';

// -------------------------------------
// GPX Cache Type Mapping
// -------------------------------------

const GPX_CACHE_TYPES = {
     1 : 'undefined',
     2 : 'Traditional Cache',
     3 : 'Multi-cache',
     4 : 'Virtual Cache',
     5 : 'Letterbox Hybrid',
     6 : 'Event Cache',
     7 : '7: undefined',
     8 : 'Unknown Cache',
     9 : 'Project A.P.E',
    10 : '10: undefined',
    11 : 'Webcam Cache',
    12 : 'Locationless (Reverse) Cache',
    13 : 'Cache In Trash Out Event',
   137 : 'Earthcache',
   453 : 'Mega-Event',
  1304 : 'GPS Adventures Exhibit',
  1858 : 'Wherigo Cache',
  3333 : 'Lab Cache',
  3653 : 'Community Celebration Event',
  3773 : 'Geocaching HQ',
  3774 : 'Geocaching HQ Celebration',
  4738 : 'Geocaching HQ Block Party',
  7005 : 'Giga-Event'
};

// -------------------------------------
// GPX Container Type Mapping
// -------------------------------------

const GPX_CONTAINER_TYPES = {
  1 : 'Not chosen',
  2 : 'Micro',
  3 : 'Regular',
  4 : 'Large',
  5 : 'Virtual',
  6 : 'Other',
  8 : 'Small',
};

// -------------------------------------
// Reference Code Conversion
// -------------------------------------

function convertGC(src, srcAlphabet, dstAlphabet) {
  const srcBase = srcAlphabet.length;
  const dstBase = dstAlphabet.length;

  let wet = src;
  let val = 0;
  let mlt = 1;

  while (wet.length > 0) {
    const digit = wet.slice(-1);
    const digVal = srcAlphabet.indexOf(digit);
    if (digVal > -1) {
      val += mlt * digVal;
      mlt *= srcBase;
    }
    wet = wet.slice(0, -1);
  }

  wet = val;
  let ret = "";

  while (wet >= dstBase) {
    const digitVal = wet % dstBase;
    const digit = dstAlphabet.charAt(digitVal);
    ret = digit + ret;
    wet /= dstBase;
  }

  const digit = dstAlphabet.charAt(wet);
  ret = digit + ret;

  return ret;
}

function referenceCode2Id(referenceCode) {
  if (!referenceCode) return '0';

  let code = referenceCode;
  const prefix = code.substring(0, 2);
  if (prefix === 'GC') {
    code = code.replace(/S/g, '5');
    code = code.replace(/O/g, '0');
  }
  code = code.slice(2);
  const firstChar = code[0];
  let id;
  if ((code.length >= 5) || (firstChar >= 'G')) {
    const srcAlphabet = '0123456789ABCDEFGHJKMNPQRTVWXYZ';
    const dstAlphabet = '0123456789';
    id = convertGC(code, srcAlphabet, dstAlphabet) - 411120;
  } else {
    const srcAlphabet = '0123456789ABCDEF';
    const dstAlphabet = '0123456789';
    id = convertGC(code, srcAlphabet, dstAlphabet);
  }
  return String(id);
}

// -------------------------------------
// Date Formatting
// -------------------------------------

function formatDateISO(date) {
  const pad = n => n.toString().padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
}

// -------------------------------------
// GPX Header/Footer
// -------------------------------------

function gpxHeader(today) {
  return `<?xml version="1.0" encoding="utf-8"?>
<gpx xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
version="1.0" creator="GCxM"
xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd http://www.gsak.net/xmlv1/6 http://www.gsak.net/xmlv1/6/gsak.xsd"
xmlns="http://www.topografix.com/GPX/1/0">
 <desc>Geocache file generated by GCxM</desc>
 <author>GCxM</author>
 <time>${today}</time>
 <keywords>cache, geocache, groundspeak</keywords>
`;
}

function gpxFooter() {
  return '</gpx>';
}

// -------------------------------------
// Generate Waypoint GPX
// -------------------------------------

/**
 * Generate a GPX file with waypoints from cache data.
 *
 * Accepts items with varying levels of detail. Required fields:
 * - lat, lon (coordinates) - or postedCoordinates/correctedCoordinates
 * - code or referenceCode (GC code)
 *
 * Optional fields (with defaults/omission behavior):
 * - name: cache name (defaults to code)
 * - geocacheType: { id, name } (defaults to Unknown Cache)
 * - geocacheSize: { id, name } (defaults to Not chosen)
 * - difficulty, terrain: (default 1)
 * - ownerAlias, ownerCode: (default "Unknown")
 * - publishedDate: (omitted if missing)
 * - status: Active/Archived/etc (default assumes Active)
 * - location: { country, state } (omitted if missing)
 * - shortDescription, longDescription, hints: (empty if missing)
 * - foundDate, pcn, correctedCoordinates: for GSAK block
 * - favoritePoints, isPremiumOnly: for GSAK block
 *
 * @param {Array} items - Array of cache objects or marker-like objects
 * @returns {string} GPX file content
 */
export function generateWaypointGPX(items) {
  if (!items || items.length === 0) return '';

  const today = formatDateISO(new Date());
  let gpx = gpxHeader(today);

  for (const item of items) {
    const wpt = generateWaypoint(item, today);
    if (wpt) gpx += wpt;
  }

  gpx += gpxFooter();
  return gpx;
}

/**
 * Generate a single waypoint element.
 * Returns null if required fields (lat, lon, code) are missing.
 */
function generateWaypoint(item, today) {
  // Extract coordinates - support multiple formats
  const coords = extractCoordinates(item);
  if (!coords) return null;

  const { lat, lon, listingLat, listingLon, hasCC } = coords;

  // Extract code - required
  const rawCode = item.code || item.referenceCode;
  if (!rawCode) return null;

  // Determine platform from item or code prefix
  const platform = item.platform || (rawCode.startsWith('GC') ? 'GC' : rawCode.startsWith('OC') ? 'OC' : 'AL');
  const isAL = platform === 'AL';

  // For AL caches, prefix with "AL" if not already prefixed
  const code = isAL && !rawCode.toUpperCase().startsWith('AL')
    ? `AL${rawCode.toUpperCase()}`
    : rawCode;

  // Extract optional fields with defaults
  const name = escapeXml(item.name || code);
  // For AL caches, use a UUID-based ID; for others, convert from reference code
  const cacheId = isAL ? rawCode : referenceCode2Id(rawCode);
  const type = GPX_CACHE_TYPES[item.geocacheType?.id] || 'Unknown Cache';
  const size = GPX_CONTAINER_TYPES[item.geocacheSize?.id] || 'Not chosen';
  const difficulty = item.difficulty || 1;
  const terrain = item.terrain || 1;
  const owner = escapeXml(item.ownerAlias || item.owner || 'Unknown');
  // Only convert ownerCode to ID if it looks like a GC reference code
  const ownerId = item.ownerCode?.startsWith?.('PR') ? referenceCode2Id(item.ownerCode) : '0';
  const status = item.status || 'Active';
  const available = status === 'Active';
  const archived = status === 'Archived';

  // Determine symbol based on found status
  const foundDate = item.foundDate?.substring(0, 10) || '';
  const symbol = foundDate.length > 4 ? 'Geocache Found' : 'Geocache';

  // Build waypoint
  let wpt = `  <wpt lat="${lat}" lon="${lon}">\n`;

  // Optional: time (published date)
  if (item.publishedDate) {
    wpt += `    <time>${item.publishedDate}T00:00:00Z</time>\n`;
  }

  wpt += `    <name>${escapeXml(code)}</name>\n`;
  wpt += `    <desc>${name} by ${owner}, ${type} (${difficulty}/${terrain})</desc>\n`;

  // URL based on platform
  if (isAL) {
    wpt += `    <url>https://gcxm.de/alexplore?id=${rawCode}</url>\n`;
    wpt += `    <urlname>${name}</urlname>\n`;
  } else if (rawCode.startsWith('GC')) {
    wpt += `    <url>http://www.geocaching.com/seek/cache_details.aspx?wp=${rawCode}</url>\n`;
    wpt += `    <urlname>${name}</urlname>\n`;
  } else if (rawCode.startsWith('OC')) {
    wpt += `    <url>https://www.opencaching.de/viewcache.php?wp=${rawCode}</url>\n`;
    wpt += `    <urlname>${name}</urlname>\n`;
  }

  wpt += `    <sym>${symbol}</sym>\n`;
  wpt += `    <type>Geocache|${type}</type>\n`;

  // Groundspeak cache block
  wpt += `    <groundspeak:cache id="${cacheId}" available="${available}" archived="${archived}" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">\n`;
  wpt += `      <groundspeak:name>${name}</groundspeak:name>\n`;
  wpt += `      <groundspeak:placed_by>${owner}</groundspeak:placed_by>\n`;
  wpt += `      <groundspeak:owner id="${ownerId}">${owner}</groundspeak:owner>\n`;
  wpt += `      <groundspeak:type>${type}</groundspeak:type>\n`;
  wpt += `      <groundspeak:container>${size}</groundspeak:container>\n`;
  wpt += `      <groundspeak:difficulty>${difficulty}</groundspeak:difficulty>\n`;
  wpt += `      <groundspeak:terrain>${terrain}</groundspeak:terrain>\n`;

  // Optional location fields
  if (item.location?.country) {
    wpt += `      <groundspeak:country>${escapeXml(item.location.country)}</groundspeak:country>\n`;
  }
  if (item.location?.state) {
    wpt += `      <groundspeak:state>${escapeXml(item.location.state)}</groundspeak:state>\n`;
  }

  // Description fields (include even if empty)
  wpt += `      <groundspeak:short_description html="True">${escapeXml(item.shortDescription || '')}</groundspeak:short_description>\n`;
  wpt += `      <groundspeak:long_description html="True">${escapeXml(item.longDescription || '')}</groundspeak:long_description>\n`;
  wpt += `      <groundspeak:encoded_hints>${escapeXml(item.hints || '')}</groundspeak:encoded_hints>\n`;
  wpt += `    </groundspeak:cache>\n`;

  // GSAK block - only include if we have GSAK-specific data
  const gsakData = buildGsakBlock(item, today, hasCC, listingLat, listingLon, foundDate);
  if (gsakData) {
    wpt += gsakData;
  }

  wpt += `  </wpt>\n`;
  return wpt;
}

/**
 * Extract coordinates from item, supporting multiple formats.
 * hasCC (has corrected coordinates) is the primary discriminator:
 * - When true: lat/lon is the corrected position, listingLat/listingLon go into GSAK extensions
 * - When false: lat/lon is the listing position, GSAK extensions are not needed
 * Returns null if coordinates cannot be determined.
 */
function extractCoordinates(item) {
  // First, determine if we have corrected coordinates
  const hasCC = item.hasCC || !!item.correctedCoordinates;

  let lat, lon, listingLat, listingLon;

  if (hasCC && item.correctedCoordinates) {
    // Corrected coordinates exist - use them as the primary position
    lat = item.correctedCoordinates.latitude;
    lon = item.correctedCoordinates.longitude;
    // Listing coordinates for GSAK LatBeforeCorrect/LonBeforeCorrect
    listingLat = item.postedCoordinates?.latitude;
    listingLon = item.postedCoordinates?.longitude;
  }
  // Format 1: Direct lat/lon or lat/lng (from markers - already at correct position)
  else if (item.lat !== undefined && (item.lon !== undefined || item.lng !== undefined)) {
    lat = item.lat;
    lon = item.lon ?? item.lng;
    // No corrected coordinates, so no listing coordinates needed
    listingLat = undefined;
    listingLon = undefined;
  }
  // Format 2: postedCoordinates without correctedCoordinates
  else if (item.postedCoordinates) {
    lat = item.postedCoordinates.latitude;
    lon = item.postedCoordinates.longitude;
    // No corrected coordinates, so no listing coordinates needed
    listingLat = undefined;
    listingLon = undefined;
  }
  // Format 3: getLatLng() method (Leaflet markers)
  else if (typeof item.getLatLng === 'function') {
    const latlng = item.getLatLng();
    lat = latlng.lat;
    lon = latlng.lng;
    // No corrected coordinates, so no listing coordinates needed
    listingLat = undefined;
    listingLon = undefined;
  }

  if (lat === undefined || lon === undefined) return null;

  return { lat, lon, listingLat, listingLon, hasCC };
}

/**
 * Build GSAK extension block if relevant data exists.
 * LatBeforeCorrect/LonBeforeCorrect are only included when hasCC is true.
 * Returns null if no GSAK-specific data.
 */
function buildGsakBlock(item, today, hasCC, listingLat, listingLon, foundDate) {
  const favpoints = item.favoritePoints;
  const pmo = item.isPremiumOnly;
  const note = item.pcn;
  const isAL = item.platform === 'AL';

  // Only include GSAK block if we have any GSAK-relevant data
  // hasCC now only contributes to this check if we have valid listing coordinates
  const hasListingCoords = hasCC && listingLat !== undefined && listingLon !== undefined;
  // Always include GSAK block for AL caches (to set FavPoints=-1)
  const hasGsakData = isAL || favpoints != null || pmo !== undefined || hasListingCoords || foundDate || note;
  if (!hasGsakData) return null;

  let gsak = `    <gsak:wptExtension xmlns:gsak="http://www.gsak.net/xmlv1/6">\n`;
  gsak += `      <gsak:Watch>false</gsak:Watch>\n`;
  gsak += `      <gsak:IsPremium>${pmo ? 'true' : 'false'}</gsak:IsPremium>\n`;

  // FavPoints: use -1 for AL caches with null favoritePoints
  if (favpoints != null) {
    gsak += `      <gsak:FavPoints>${favpoints}</gsak:FavPoints>\n`;
  } else if (isAL) {
    gsak += `      <gsak:FavPoints>-1</gsak:FavPoints>\n`;
  }

  gsak += `      <gsak:GcNote>${escapeXml(note || '')}</gsak:GcNote>\n`;

  if (hasListingCoords) {
    gsak += `      <gsak:LatBeforeCorrect>${listingLat}</gsak:LatBeforeCorrect>\n`;
    gsak += `      <gsak:LonBeforeCorrect>${listingLon}</gsak:LonBeforeCorrect>\n`;
  }
  if (foundDate) {
    gsak += `      <gsak:UserFound>${foundDate}</gsak:UserFound>\n`;
  }

  gsak += `    </gsak:wptExtension>\n`;

  // Add cgeo extension for AL caches
  if (isAL) {
    gsak += `    <cgeo:cacheExtension xmlns:cgeo="http://www.cgeo.org/xmlv1/1">\n`;
    gsak += `      <cgeo:assignedEmoji>0</cgeo:assignedEmoji>\n`;
    gsak += `    </cgeo:cacheExtension>\n`;
  }

  return gsak;
}

// -------------------------------------
// Generate Track GPX
// -------------------------------------

/**
 * Generate a GPX file with a track from route segments.
 *
 * @param {Array} segments - Array of segments, each with routeCoordinates array
 * @param {string} [trackName='GCxM Track'] - Optional name for the track
 * @returns {string} GPX file content
 */
export function generateTrackGPX(segments, trackName = 'GCxM Track') {
  if (!segments || segments.length === 0) return '';

  let gpx = '<?xml version="1.0" encoding="UTF-8"?>\n';
  gpx += '<gpx version="1.1" creator="GCxM - Geocaching eXtended Manager">\n';
  gpx += '  <trk>\n';
  gpx += `    <name>${escapeXml(trackName)}</name>\n`;
  gpx += '    <trkseg>\n';

  for (const segment of segments) {
    if (!segment.routeCoordinates) continue;
    for (const latlng of segment.routeCoordinates) {
      gpx += `      <trkpt lat="${latlng.lat}" lon="${latlng.lng}">`;
      if (latlng.ele !== undefined) {
        gpx += `<ele>${latlng.ele}</ele>`;
      }
      gpx += `</trkpt>\n`;
    }
  }

  gpx += '    </trkseg>\n';
  gpx += '  </trk>\n';
  gpx += '</gpx>';

  return gpx;
}

//-------------------------------------------------------
// getMultiContent()
//
async function getMultiContent(content) {
  const {files} = content;
  if (!files) return;

  const boxContent = document.getElementById('box-content');
  const spinner    = document.getElementById('spinner');

  boxContent.style.visibility = 'visible';
  spinner.style.visibility    = 'visible';

  let index = 0;
  for (let file of files) {
    let {name, size} = file;
    await process(file, name, index++);
  }
  spinner.style.visibility = 'hidden';
  addLine('<b>all files processed</b>');
}

//-----------------------------------------------------------------------
// process()
//
// handle a single file

async function process(file, name, index) {
  const shortName = name.substring(0, 20) + ' ...';
  let fileContent;

  try {
    fileContent = await readFileAsync(file);
  } catch (err) {
    addLine(`${shortName} : read() failed<br>`);
    return;
  }

  const options = {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      data: fileContent,
      cc: document.getElementById('cb_cc').checked,
      pcn: document.getElementById('cb_pcn').checked
    })
  };

  try {
    const result = await apiFetch('gpx', options, { raw: true }); // raw true returns full Response

    if (result.status === 204) {
      addLine(`imported: ${String(index + 1).padStart(4, ".")} ${shortName}`);
    } else if (result.status === 200) {
      const data = await result.text();
      addLine(`failed:   ${String(index + 1).padStart(4, ".")} ${shortName} ${data}`);
    }
  } catch (error) {
    addLine(`failed:   ${String(index + 1).padStart(4, ".")} ${shortName} ${error.message}`);
  }
}

//-----------------------------------------------------------------------
// readFileAsync()

function readFileAsync(file) {
  return new Promise((resolve, reject) => {
    let reader = new FileReader();

    reader.onload = () => {
      resolve(reader.result);
    };

    reader.onerror = reject;
    reader.readAsText(file, 'UTF-8');
  })
}

//----------------------------------------------------------------------------
// addline()
//
// ... and take care of scrolling the box

const addLine = (text) => {
  const boxContent = document.getElementById('box-content');
  boxContent.innerHTML += text + '<br>';
  boxContent.scrollTop = boxContent.scrollHeight;
};

//----------------------------------------------------------------------------
//
function init() {
  const input = document.getElementById('getMultiContent');
  if (input) input.addEventListener('change', () => getMultiContent(input));
}

init();

// -------------------------------------
// Exports
// -------------------------------------

export {
  GPX_CACHE_TYPES,
  GPX_CONTAINER_TYPES,
  referenceCode2Id,
};

// code: language=javascript insertSpaces=true tabSize=2
// vim: ts=2:sw=2:et:ft=javascript
