<?php

// autoload.php @generated by Composer

use okapi\Settings;

require_once __DIR__ . '/vendor/autoload.php';

function get_admin_emails()
{
    $emails = array();
    if (class_exists(Settings::class))
    {
        try
        {
            foreach (Settings::get('ADMINS') as $email)
                if (!in_array($email, $emails))
                    $emails[] = $email;
        }
        catch (Exception $e) { /* pass */ }
    }
    if (count($emails) == 0)
        $emails[] = 'root@localhost';
    return $emails;
}
