<?php
/***************************************************************************
 * for license information see LICENSE.md
 *
 *
 *  Constant definitions
 ***************************************************************************/

require_once __DIR__ . '/../lib/consts-common.inc.php';

define('DEBUG_NO', 0);
define('DEBUG_DEVELOPER', 1);
define('DEBUG_TEMPLATES', 2);
define('DEBUG_OUTOFSERVICE', 4 | DEBUG_TEMPLATES);
define('DEBUG_TESTING', 8 | DEBUG_TEMPLATES);
define('DEBUG_SQLDEBUGGER', 16);
define('DEBUG_TRANSLATE', 32); // DEBUG_TEMPLATES added in common.inc.php
define('DEBUG_FORCE_TRANSLATE', 64 | DEBUG_TRANSLATE);
define('DEBUG_CLI', 128);

define('PHP_DEBUG_OFF', 0);
define('PHP_DEBUG_ON', 1);
define('PHP_DEBUG_SKIP', - 1);

define('SAVE_COOKIE', 0);
define('SAVE_SESSION', 1);

define('DB_MODE_FRAMEWORK', 0);
define('DB_MODE_BUSINESSLAYER', 1);
define('DB_MODE_USER', 2);
define('DB_DATE_FORMAT', '%Y-%m-%d %H:%M:%S');

define('ID_NEW', - 1);

define('RE_TYPE_INT', 1);
define('RE_TYPE_STRING', 2);
define('RE_TYPE_BOOLEAN', 3);
define('RE_TYPE_DATE', 4);
define('RE_TYPE_FLOAT', 5);
define('RE_TYPE_DOUBLE', 6);

define('RE_INSERT_NOTHING', 0); //
define('RE_INSERT_OVERWRITE', 1); // ignore given values and use function
define('RE_INSERT_IGNORE', 2); // dont use this column on insert
define('RE_INSERT_AUTOINCREMENT', 4); // column is an auto increment column
define('RE_INSERT_AUTOUUID', 8); // if empty, UUID is generated by before insert trigger (not supported for primary key fields)
define('RE_INSERT_NOW', 16); // NOW()
