<div class="content2-pagetitle"><img style="MARGIN-RIGHT: 10px; align: left" height="32" alt="" src="resource2/{$opt.template.style}/images/cacheicon/traditional.gif" width="32" />Acerca de Geocaching </div>
<div class="content-txtbox-noshade" style="PADDING-RIGHT: 25px">
  <p><img style="MARGIN-LEFT: 5px" alt="Über Geocaching" src="images/ueber.jpg" align="right" /></p>
  <p align="justify">Geocaching ha sido descrito como la búsqueda del   tesoro moderno. En pocas palabras : hay personas que  esconden contenedores con obsequios y un cuaderno o libro de registro. Y las coordenadas del escondite son publicadas en la   web.</p>
  <p align="justify">En la web  tomó nota de esas coordenadas y las introduzco en el dispositivo GPS para comenzar la busqueda de los tesoros. A continuación, una vez encontrado, hago un pequeño intercambio de los obsequios que hay en el contenedor, registro  la visita en el cuaderno y vuelvo a esconderno en el mismo lugar   - para los próximos jugadores...</p>
  <p align="justify">Esas son las reglas básicas. Pero por supuesto hay mucho más detrás de esta actividad.   Por ejemplo, hay diferentes tipos de caches, como los caches sencillos, a los que puedo acceder a ellos sin bajarme del coche, otros que sólo son accesibles con   un equipo especial (por ejemplo, escalar o equipo de snorkel), o podemos encontrarnos con los llamados los puzzle   caches que requieren realizar alguna investigación y resolver puzzles   de lógica.</p>
  <p align="justify">Pero siempre hay un denominador común: divertirse haciendo  Geocaching. Diversión cuando escondas un tesoro. Diversión en la búsqueda y resolver misterios o puzzles de   lógica. Diversión en el desafío. Y podrás disfrutar en el intercambio de ideas con otros geobuscadores - en las entradas de registro de un cache, en los distintos sitios web sobre geoaching, foros o incluso en   las reuniones, llamadas Events Caches.</p>
  <p align="justify">La fascinación del Geocaching es difícil llegar al punto,   son los diferentes tipos de caché, tan variados y saludables como   los paisajes en los que caches están ocultos, tan diferentes son los tipos   Geobuscadores: Mientras que algunos Geobuscadores crean un tesoro como un incentivo adicional   para los deportes como el senderismo, otros utilizan el encanto de la búsqueda del   tesoro sólo para sus hijos (o usted mismo ;-) para invitar a realizar viajes. <span id="result_box" lang="es" xml:lang="es"><span title="" closure_uid_obbxjb="80" ed="Die einen reizt besonders die Knobelei und das Suchen, andere hassen genau dies, denn für sie liegt der Spass eher darin, sich durch unwegsames Gelände zu kämpfen oder einfach nur schöne Touren zu machen und die reine Schatzsuche dabei nur als kleine Nebenfreude 'mitzunehmen'." fd="Algunas personas encuentran especialmente atractivo para resolver puzzles de lógica y la búsqueda, otros de odio sólo eso, porque para ellos la diversión está más bien en tener que vadear a través de terrenos difíciles, o simplemente para hacer excursiones a la búsqueda del tesoro puro aquí sólo como una pequeña adición a la alegría 'tomar'.">Algunas   personas encuentran especialmente atractivo el resolver puzzles de lógica y la posterior  búsqueda, otros  odio ese tipo de puzzle-caches, porque para ellos la diversión está más bien   en tener que buscar a través de terrenos difíciles, o simplemente para hacer   excursiones a la  búsqueda del tesoro donde la alegría de jugador es 'encontrar'.</span></span></p>
  <p align="justify">¿Todo esto te suena completamente absurdo y tal vez muy sentimental? Bueno, te invitamos a probarlo - y hablamos de nuevo   ...</p>
  <p align="justify">&nbsp;</p>
  <p align="justify">Este texto es de <a href="http://www.geocaching.de" target="_blank">http://www.geocaching.de</a> - ¡Gracias!</p>
</div>
