{***************************************************************************
 *  You can find the license in the docs directory
 *
 *  Unicode Reminder メモ
 ***************************************************************************}
{t}Hello{/t}{if $username!=''} {$username}{elseif $login.username!=''} {$login.username}{/if},
 
{include file="$template.tpl"}

--
{$opt.page.absolute_url}

{t 1=$opt.mail.contact}This E-Mail was generated by the opencaching.de website, because an account with
this E-Mail address was created. If you don't want to receive E-Mails in future, 
please contact us via E-Mail %1{/t}
