# crowdin.yml for Crowdin CLI 3
"project_id" : "186510"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

# Your personal access tokens can be found at https://crowdin.com/settings
# Store your token to the environment variable CROWDIN_PERSONAL_TOKEN
#  Example for fish: set -Ux CROWDIN_PERSONAL_TOKEN your_token
#  Example for bash (in ~/.bashrc): export CROWDIN_PERSONAL_TOKEN="your_token"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

"preserve_hierarchy": true

files: [
  {
    "source": "/app/Resources/translations/constants.en.yml",
    "translation": "/app/Resources/translations/constants.%two_letters_code%.yml",
  },
  {
    "source": "/app/Resources/translations/messages.en.yml",
    "translation": "/app/Resources/translations/messages.%two_letters_code%.yml",
  },
  {
    "source": "/app/Resources/translations/validators.en.yml",
    "translation": "/app/Resources/translations/validators.%two_letters_code%.yml",
  },
  {
    "source": "/app/Resources/translations/legacycode/oc_legacy.csv",
    "translation": "/app/Resources/translations/legacycode/oc_legacy.%two_letters_code%.csv",
  }
]
