# crowdin.yml for Crowdin CLI 3
# see https://opencaching.atlassian.net/wiki/spaces/TRA/pages/5734402/Translation+Handling+Legacy#Import-translations-with-Crowdin-CLI-V3

"project_id" : "186510"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

"api_token_env": "CROWDIN_PERSONAL_TOKEN"

"preserve_hierarchy": true

files: [
  {
    "source": "/app/Resources/translations/constants.en.yml",
    "translation": "/app/Resources/translations/constants.%two_letters_code%.yml",
  },
  {
    "source": "/app/Resources/translations/messages.en.yml",
    "translation": "/app/Resources/translations/messages.%two_letters_code%.yml",
  },
  {
    "source": "/app/Resources/translations/validators.en.yml",
    "translation": "/app/Resources/translations/validators.%two_letters_code%.yml",
  },
  {
    "source": "/app/Resources/translations/legacycode/oc_legacy.csv",
    "translation": "/app/Resources/translations/legacycode/oc_legacy.%two_letters_code%.csv",
  }
]
