project_identifier: opencaching
base_url: https://api.crowdin.com #Your personal key can be found at https://crowdin.com/project/opencaching/settings#api
api_key:
base_path: /var/www/html/htdocs/

files:
  -
    source: /app/Resources/translations/constants.en.yml
    translation: /app/Resources/translations/constants.%two_letters_code%.yml
  -
    source: /app/Resources/translations/messages.en.yml
    translation: /app/Resources/translations/messages.%two_letters_code%.yml
