{***************************************************************************
* You can find the license in the docs directory
***************************************************************************}
<div class="content2-pagetitle">
    <img src="resource2/{$opt.template.style}/images/profile/32x32-security.png" style="margin-right: 10px;" width="32" height="32" alt="" />Privacy statement
</div>
<div class="content-txtbox-noshade" style="padding-right: 25px;">

<p><i>This is a tentative English translation of the German privacy statement for this website, which is available by selecting German language and choosing "Datenschutzbelehrung" at the very bottom of the page. When in doubt, or the translation is incomplete or contradicting, the German version is always the valid reference for legal issues. This explanation refers to all Geocaching listing sites operated by Opencaching Deutschland: www.opencaching.de, www.opencaching.it, www.opencachingspain.es and www.opencaching.fr.</i>
</p>

<p>We respect your right of informational self-determination. According to German TMG, title 13, and BDSG, title 33, part 1 we explain here which data will be stored by us for which purpose, and how you can inspect the data or have it deleted.</p>

<h2>User account</h2>

<p>Some services of the Opencaching.de website require a user registration. When registering, you <strong>must</strong> enter</b></p>

<ul class="narrowlist">
    <li>a user name of your choice,</li>
    <li>a valid email address, and</li>
    <li>a password of your choice.</li>
</ul>

<p>This data will be stored in your user profile, together with the date and time of your registration.</p>

<p>Besides of this, you may enter the following <strong>optional</strong> data in your user profile:</p>

<ul class="narrowlist">
    <li>first and last name</li>
    <li>home coordinates</li>
    <li>home country</li>
    <li>home town</li>
    <li>age</li>
</ul>

<p>We will also record the date and time of your account creation and of your last visit at our website.</p>

<p>We will never pass on your email address and/or name to third parties without your explicit request.</p>

<p>Your user name, home country, coordinates, all data marked as "visible" on the "details" page of your user profile and your registration date can be viewed by any visitors of the Opencaching.de website and may be requested by and transferred to third parties and other websites, e.g. for creating geocaching statistics. For registered Opencaching.de users, your home location is also visible. However, we reserve the right to deny access to this data by anyone whose intentions may be harmful for you or Opencaching.de. If you do not agree with transfering these data to third parties, you should either enter no data (not applicable to user name and date/time) or e.g. enter inaccurate coordinates.</p>

<p>Your first and last name (if entered) and email address are visible for members of Opencaching.de support team and for system administrators. The password is stored encoded in a way which makes it unreadable and not reconstructible.</p>

<p>Cache listings, log entries and published pictures are no private data and may be passed on to third parties.</p>

<h2>Cookies</h2>

<p>Opencaching.de stores several <a href="http://de.wikipedia.org/wiki/HTTP-Cookie" target="_blank">cookies</a> in your web browser. They contain information on the website state as chosen
by you, e.g. login status, language and editor preferences. This way, the Opencaching site
will behave the same after you leave it and come back.</p>

<p>For detailed information, see the developers' <a href="https://github.com/OpencachingDeutschland/oc-server3/tree/stable/doc/cookies.txt">cookie documentation</a>.</p>

<h2>Google Analytics</h2>

<p>This website uses Google Analytics, a web analysis service of Google Inc, (1600 Amphitheatre Parkway Mountain
    View, CA 94043, USA; &quot;Google&quot;). The use includes the &quot;Universal Analytics&quot; operating mode.
    This facilitates the assignment of data, sessions and interactions across several devices to a pseudonymous user
    ID and thus the analysis of a user's activities across devices. This data protection notice is provided by <a
        href="https://www.intersoft-consulting.de" target="_blank">www.intersoft-consulting.de</a>.</p>

<p>Google Analytics uses &quot;cookies&quot;, which are text files placed on your computer, to allow the website
    operator to analyze how users use the site. The information generated by the cookie about your use of this
    website is usually transferred to a Google server in the USA and stored there. However, if IP anonymisation is
    activated on this website, Google will reduce your IP address within Member States of the European Union or in
    other states party to the Agreement on the European Economic Area beforehand. Only in exceptional cases will the
    full IP address be transmitted to a Google server in the USA and shortened there. The IP address transmitted by
    your browser in the context of Google Analytics is not merged with other Google data. On behalf of the operator
    of this website, Google will use this information to evaluate your use of the website, to compile reports on
    website activity and to provide the website operator with other services related to website and Internet use.
    Our legitimate interest in data processing also lies in these purposes. The legal basis for the use of Google
    Analytics is § 15 para. 3 TMG and Art. 6 para. 1 lit. f GDPR. Sessions and campaigns are terminated after a
    certain period of time. By default, sessions are closed after 30 minutes without activity and campaigns after
    six months. The time limit for campaigns may not exceed two years. For more information on terms of use and data
    protection, please visit <a href="https://www.google.com/analytics/terms/gb.html" target="_blank">https://www.google.com/analytics/terms/gb.html</a>
    or <a href="https://policies.google.com/?hl=en" target="_blank">https://policies.google.com/?hl=en</a>.</p>

<p>You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that
    if you do this you may not be able to use the full functionality of this website. You can also prevent Google
    from collecting the data generated by the cookie and relating to your use of the website (including your IP
    address) and from processing this data by Google by downloading and installing the <a
        href="https://tools.google.com/dlpage/gaoptout?hl=en">Browser Add-on</a>. Opt-out cookies prevent the future
    collection of your data when you visit this website. To prevent Universal Analytics from collecting data across
    several devices, you must opt-out on all systems used. If you click here, the opt-out cookie will be set: <a
        href="javascript:gaOptout()"><strong>Disable Google Analytics</strong></a></p>

<h2>Webserver protocols</h2>

<p>Like any webserver, Opencaching.de keeps a protocol of all requested pages. For each request,
it contains the user's IP address, date and time, address (URL) of the requested page,
the transferred data amount and the identification of the web browser used. It does <em>not</em>
contain the user name or any other information from the Opencaching.de user account.</p>

<p>The protocol is kept for some weeks back; older entries are automatically deleted.
It is accessible only for server administratores of Opencaching.de and will be used solely
for statistical purposes and for diagnosis of technical problems.</p>

<p>Also, there is a protocol of emails sent by the Opencaching software, e.g. messages
about new caches and logs. It contains data for the last 30 days, is accessible only
for system admins and will only be used for diagnoses of email delivery problems.</p>

<h2>Inspecting your stored data</h2>

<p>After logging in, you can view and change your data at the "My Profile" page.
You can also see your registration date there.</p>
<p>You can inspect the stored cookies within your web browser.</p>

<h2>Deleting your stored data</h2>

<p>You can always delete all optional data from your user profile, and you can change
the mandantory user name, email address and password as you like (as long as the email address stays valid).</p>

<p>Accounts of users who did find or log caches cannot be deleted. Hovever, they can be disabled. Disabling includes deletion of all data, including the email address, from the user profile. The user name, cache listings and logs will be retained and stay visible, but the listings will be locked and cannot be logged from thereon. If you desire to disable your Opencaching.de account, please send an email to <a href="mailto:{$opt.mail.contact}">{$opt.mail.contact}</a> and using the email address specified in your profile. We then will disable your account.</p>

<p>To allow for fixing operating errors, the personal data will be kept for two weeks after user deactivation, before they are finally deleted.</p>

<p>A user deactivation cannot be reversed. If you would like to use Opencaching.de thereafter,
you will have to register again with a new user name and eventually re-list your caches.</p>

<p>You may delete the cookies in your web browser.</p>

<p>For questions or when in doubt, please contact us at <a href="mailto:{$opt.mail.contact}">{$opt.mail.contact}</a>!</p>
</div>
<br />
